DROP TABLE IF EXISTS name_clean_up CASCADE;

CREATE TABLE name_clean_up (
	item_id serial PRIMARY KEY,
	order_name varchar(100),
	sticker_name varchar(100),
	base_case numeric(5,2)
);

INSERT INTO name_clean_up (order_name, sticker_name, base_case)
VALUES
('ACORN SQUASH RED', 'Acorn Squash',40),
('BRAEBURN APPLE', 'Apple - Braeburn',40),
('BRAEBURN APPLE 40 LB BOX', 'Apple - Braeburn',40),
('FUJI APPLE', 'Apple - Fuji',40),
('FUJI APPLES 40 LBS', 'Apple - Fuji',40),
('APPLES GOLDEN DELICIOUS', 'Apple - Golden',40),
('APPLES  GOLDEN DELICIOUS', 'Apple - Golden Delicious',40),
('APPLES GOLDEN CRUNCHY DELICIOUS 40 LB', 'Apple - Golden Delicious',40),
('APPLES GOLDEN DELICIOUS 40 LB BOX', 'Apple - Golden Delicious',40),
('GRANNY SMITH APPLES', 'Apple - Granny Smith',40),
('1GRAPP', 'Apple - Granny Smith',40),
('Granny Smith Apple', 'Apple - Granny Smith',40),
('GRANNY SMITH APPLES 40 LB BOX', 'Apple - Granny Smith',40),
('GREEN  APPLES', 'Apple - Green',40),
('GREEN APPLES', 'Apple - Green',40),
('Green Apple', 'Apple - Green',40),
('GREEN APPLES 40 LB', 'Apple - Green',40),
('GREEN APPLES 40 LB BOX', 'Apple - Green',40),
('JONAGOLD APPLE 46#', 'Apple - Jonagold',40),
('MACINTOSH  APPLES', 'Apple - Macintosh',40),
('MACINTOSH APPLES', 'Apple - Macintosh',40),
('MACINTOSH APPLES 40  LB BOX', 'Apple - Macintosh',40),
('MACINTOSH APPLES 40 LB BOX', 'Apple - Macintosh',40),
('APPLES  RED  DELICIOUS  4-0LBS', 'Apple - Red Delicious',40),
('APPLES RED DELICIOUS 40 LBS', 'Apple - Red Delicious',40),
('APPLES RED DELICIOUS 40 LB_S', 'Apple - Red Delicious',40),
('YELLOW APPLE', 'Apple - Yellow',40),
('GALA APPLES', 'Apple Gala',40),
('GALA APPLES 40 LBS', 'Apple Gala',40),
('APPLES GOLDEN DELICIOUS 40 LB', 'Apples - Golden',40),
('HONEY CRISPS APPLES 40 LBS', 'Apples - Honeycrisp',20),
('APPLES RED DELICIOUS', 'Apples - Red Delicious',40),
('FRESH APRICOTS 24 LBS', 'Apricots',21),
('FRESH ARTICHOKE 20 LB BOX', 'Artichoke',20),
('ARUGULA', 'Arugula',3),
('FRESH ARUGULA 4LB BOX', 'Arugula - 4 lb box',3),
('ROCKET SALAD/ARUGULA 3#', 'Arugula Baby',3),
('FRESH ARUGULA', 'Arugula, Baby',3),
('ASIAN PEARS (APPROX 40#)', 'Asian Pears (approx 40#)',40),
('ASPARAGUS', 'Asparagus',11),
('FRESH ASPARAGUS', 'Asparagus',11),
('FRESH ASPARAGUS 11 LB BOX', 'Asparagus',11),
('FRESH AVOCADO (20#)', 'Avocado',25),
('FRESH AVOCADO (20#} HALF RIPE', 'Avocado',25),
('HAAS AVOCADO', 'Avocado',25),
('FRESH AVOCADO (10# BX', 'Avocado',25),
('FRESH AVOCADO (10# BX)', 'Avocado',25),
('FRESH AVOCADO (10# BX) NOT RIPE', 'Avocado',25),
('FRESH AVOCADO (20#', 'Avocado',25),
('FRESH AVOCADO (20)', 'Avocado',25),
('FRESH AVOCADO (25 LB/BX)', 'Avocado',25),
('ARUGULA 8 OZ', 'Baby Arugula',3),
('RUCOLLA 3#', 'Baby Arugula',3),
('ARUGALA', 'Baby Arugula (3.5 lb/box)',3),
('ARUGULA (3 POUND/BOX)', 'Baby Arugula (3.5 lb/box)',3),
('BABY ARUGULA (3.5 LB/BOX)', 'Baby Arugula (3.5 lb/box)',3),
('ROCKET SALAD BABY ARUGA;A', 'Baby Arugula (3.5 lb/box)',3),
('ROCKET LETTUCE', 'BABY ARUGULA (ROCKET)',3),
('PITCHAY', 'Baby Bok Choy',30),
('FRESH BABY SPINACH CLEANED', 'Baby Spinach',10),
('Banana', 'Banana',40),
('BANANAS GREEN 40 LB BOX', 'Banana',40),
('BANANAS GREEN 40 LB/BX', 'Banana',40),
('BANANAS HALF RIPE 40 LB BOX', 'Banana',40),
('BANANAS RIPE 40 LB BOX', 'Banana',40),
('BANANAS', 'Banana',40),
('BANANAS  HALF  RIPE', 'Banana',40),
('BANANAS HALF RIPE', 'Banana',40),
('BANANAS HALF RIPE GREEN', 'Banana',40),
('BANANAS RIPE', 'Banana',40),
('BANANAS * GREEN 40 LB BOX', 'Banana - **Green**',40),
('BANANAS GREEN', 'Banana - Green',40),
('BANANAS HALF RIPE', 'Banana - Half Ripe',40),
('FRESH BASIL 2.5 LB  BAG           *CANNOT BRK BAG OF 1.14kg.*', 'Basil',2.5),
('FRESH BASIL 2.5 LB BAG', 'Basil',2.5),
('FRESH BASIL 2.6 LB BAG', 'Basil',2.5),
('LIMA BROAD BEAN', 'Bean - Lima Broad',null),
('LONG BEANS', 'Bean - Long',null),
('SNAP BEAN SITAO PEA', 'Bean - Snap Sitao Pea',null),
('BEAN  SPROUTS', 'Bean Sprouts',10),
('BEAN SPROUTS', 'Bean Sprouts',10),
('BEAN SPROUTS 10 LB BX', 'Bean Sprouts',10),
('BROAD BEANS FRESH', 'Beans Broad',null),
('FRENCH BEANS 5 LB BOX', 'Beans French 5 lb',null),
('WAX BEANS / YELLOW BEANS', 'Beans Wax',null),
('BEET ROOT', 'Beet Root',25),
('BEET ROOT 25 LB BOX', 'Beet Root',25),
('BEET ROOT LARGE', 'Beet Root',25),
('BITTER MELON/GOURD', 'Bitter Melon/Gourd',30),
('BITTER MELON1GOURD', 'Bitter Melon/Gourd',30),
('BITTER MELONIGOURD', 'Bitter Melon/Gourd',30),
('Bitter Melon', 'Bitter Melon/Gourd',30),
('BLUEBERRIES  (12 PTS)', 'Blueberries',12),
('BLUEBERRIES (12 PTS)', 'Blueberries',12),
('BOC   CHOI  FR.ESH', 'Bok Choy',40),
('BOC   CHOI  FRESH', 'Bok Choy',40),
('BOC CHOI', 'Bok Choy',40),
('BOC CHOI FRESH', 'Bok Choy',40),
('BOC CHOI FRESH 40 LB BOX', 'Bok Choy',40),
('BOO CHOI FRESH', 'Bok Choy',40),
('BOC CHOI', 'Bok Choy',40),
('BABY BOC CHOI FRESH (SMALL)', 'Bok Choy Baby',30),
('BABY BOC CHOY 30#', 'Bok Choy Baby',30),
('SMALL BOC CHOI FRESH', 'Bok Choy Baby',30),
('BOC CHOI FRESH 40 LB *BABY', 'Bok Choy Baby',30),
('BOTTLE GOURD', 'Bottle Gourd',30),
('BROCCOLI', 'Broccoli',20),
('FRESH  BROCCOLI', 'Broccoli',20),
('FRESH BROCCOLI', 'Broccoli',20),
('FRESH BROCCOLI 22 LB BOX', 'Broccoli',20),
('Brocolli', 'Broccolli',35),
('BRUSSEL SPROUTS', 'Brussels Sprouts',25),
('BRUSSEL SPROUTS 25 LB BOX', 'Brussels Sprouts',25),
('BUTTERNUT SQUASH 45 LB BOX', 'Butternut Squash',40),
('BUTTERNUT SQUASH 45LB WHITE', 'Butternut Squash',40),
('RED BUTTERNUT SQUASH', 'Butternut Squash - Red',40),
('BUTTERNUT SQUASH WHITE', 'Butternut Squash - White',40),
('CHINESE  CABBAGE', 'Cabbage - Chinese',40),
('CHINESE CABBAGE', 'Cabbage - Chinese',40),
('CHINESE CABBAGE 40 LB BOX', 'Cabbage - Chinese Napa',40),
('GREEN CABBAGE', 'Cabbage - Green',50),
('GREEN CABBAGE 50 LB BOX', 'Cabbage - Green',50),
('NAPPA CABBAGE 40 LB BOX', 'Cabbage - Napa',40),
('NAPPA CABBAGE', 'Cabbage - Napa',40),
('PURPLE CABBAGE', 'Cabbage - Purple',50),
('RED CABBAGE', 'Cabbage - Red',50),
('RED CABBAGE 50 LB BOX', 'Cabbage - Red',50),
('CABBAGE SAVOY', 'Cabbage - Savoy',35),
('SAVOY CABBAGE', 'Cabbage - Savoy',35),
('WHITE CABBAGE ''SAVOY""', 'Cabbage - Savoy',35),
('WHITE CABBAGE SHREDDED', 'Cabbage - shredded',50),
('VVHITE  CABBAGE', 'Cabbage - White',50),
('WHITE CABBAGE', 'Cabbage - White',50),
('WHITE CABBAGE 50 LB BOX', 'Cabbage - White',50),
('WHITE CABBAGE 60 LB BOX', 'Cabbage - White',50),
('CANTALOUPES', 'Cantaloupe',35),
('CANTALOUPES 40 LB BOX', 'Cantaloupe',35),
('CAR.ROTS  TOPPED', 'Carrot',40),
('CARROTS  TOPPED', 'Carrot',40),
('CARROTS TOPPED', 'Carrot',40),
('CARROTS TOPPED 50 LB', 'Carrot',40),
('CARROTS TOPPED 60 LB BAG', 'Carrot',40),
('BABY CARROTS', 'Carrot - Baby',40),
('CARROTS TOPPED 50 LB BAG', 'Carrot - Loose',40),
('CARROTS TOPPED MEDIUM SIZE', 'Carrot - Med',40),
('CASSAVA', 'Cassava',30),
('CASSAVA ROOT', 'Cassava Root',30),
('FRESH CASSAVA', 'Cassava Root',30),
('FRESH CASSAVA ROOT', 'Cassava Root',30),
('CAULIFLC>VVER  TRIM  VVRAP', 'Cauliflower',20),
('CAULIFLOVVER   TRIM  VVRAP', 'Cauliflower',20),
('CAULIFLOVVER  TRIM  VVRAP', 'Cauliflower',20),
('CAULIFLOWER TRIM WRAP', 'Cauliflower',20),
('CAULIFLOWER TRIM WRAP 20 LB', 'Cauliflower',20),
('CAULIFLOWER TRIM WRAP 20 LB   BOX', 'Cauliflower',20),
('CAULIFLOWER TRIM WRAP 20 LB/BX', 'Cauliflower',20),
('CELERY', 'Celery',20),
('CELERY 50 LB BAG', 'Celery',20),
('CELERY ROOT', 'Celery Root',20),
('FR.ESH  CHAYOTE', 'Chayote',10),
('FRESH CHAYOTE', 'Chayote',10),
('FRESH CHAYOTE 10 LB BOX', 'Chayote',10),
('CHERRIES', 'Cherries',15),
('CHERRIES 18 LB BOX', 'Cherries',15),
('CHERRY TOMATOES 12 LB/BX', 'Cherry Tomato',12),
('CHICORY 22#/BX', 'Chicory',22),
('HOT CHILI PEPPERS ex hot', 'Chili Peppers Red Extra Hot',25),
('CHIVES', 'Chives',2.5),
('CHIVES 2.2# BOX', 'Chives',2.5),
('FRESH CHIVES', 'Chives',2.5),
('FRESH CHIVES 2# BOX', 'Chives',2.5),
('FRESH CHIVES BUNCH', 'Chives',2.5),
('FRESH CLEMENTINES 5 LB', 'Clementines',30),
('FRESH COCONUTS', 'Coconuts',24),
('FRESH COCONUTS (OLD 4 COOKING)', 'Coconuts',24),
('CORIANDER LEAVES', 'Coriander',null),
('C::ORRIANDER   LEAVES', 'Coriander',null),
('CC>RRIANDER  LEAVES', 'Coriander',null),
('CORR.IANDER   LEAVES', 'Coriander',null),
('CORRIANDER  LEAVES', 'Coriander',null),
('CORRIANDER LEAVES', 'Coriander',null),
('FRESH  CORN  C>NCOB   t40#  AVGl', 'Corn',40),
('FRESH CORN ON COB (40# AVG)', 'Corn',40),
('CREW PRIVATE', 'Crew Private',null),
('MUSHROOM CREMINI', 'Crimini Mushroom',5),
('CUCUMBERS 50 LB BOX', 'Cucumber',50),
('CUCUMBERS 60 LB BOX', 'Cucumber',50),
('Cucumber', 'Cucumber',50),
('CUCUMBERS', 'Cucumber',50),
('CUCUMBERS HOT HOUSE', 'Cucumber - Cello',50),
('CUCUMBERS ENGLISH WRAPPED', 'Cucumber - English',50),
('CUCUMBERS KIRBY (45LB)', 'Cucumber - Kirby',50),
('CUCUMBERS LARGE', 'Cucumber - Large',50),
('CUCUMBER PERSIAN', 'Cucumber - Persian',50),
('CUCUMBERS SMALL', 'Cucumber - Small',50),
('VVHITE   DAIKON  RADISH', 'Daikon Radish',40),
('VVHITE  DAIKC>N  RADISH', 'Daikon Radish',40),
('WHITE  DAIKC>N  RADISH', 'Daikon Radish',40),
('WHITE DAIKON RADISH', 'Daikon Radish',40),
('WHITE DAIKON RADISH ROUND', 'Daikon Radish',40),
('WHITE DAIMON RADISH', 'Daikon Radish',40),
('WHITE DAIMON RAMSH. .', 'Daikon Radish',40),
('WHITE DAIKON RADISH LONG', 'Daikon Radish - Long',40),
('WHITE DAIKON RADISH 40 LB BOX', 'Daikon Radish - White',40),
('FRESH DILL', 'Dill',null),
('FRESH DILL                        *1 POUND SMALLEST SIZE AVAIL*', 'Dill',null),
('DRAGON FRUIT', 'Dragon Fruit',10),
('DRAGON FRUIT 10 # BOX', 'Dragon Fruit',10),
('DRAGON FRUIT, 10Ib PER CASE', 'Dragon Fruit',10),
('DRAGONFRUIT 10# *CANNOT BREAK*', 'Dragon Fruit',10),
('DRAGON FRUIT 10#', 'Dragon Fruit',10),
('DRAGONFRUIT', 'Dragon Fruit',10),
('FRESH DRAGONFRUIT', 'Dragonfruit',10),
('EGGPLANT', 'Eggplant',25),
('EGGPLANT 25 LB BOX', 'Eggplant',25),
('EGGPLANT LONG', 'Eggplant',25),
('EGGPLANT OBLONG', 'Eggplant',25),
('EGGPLANT SMALL SIZE', 'Eggplant - Small Size',25),
('EGGS FRESH FREE RANGE', 'Eggs Free Range',null),
('EGGS FRESH FREE RANGE XL', 'Eggs Free Range',null),
('ENDIVE 22 LBS.', 'Endive',22),
('ESCAROLE (22#/BX)', 'Escarole (22#/bx)',22),
('FRESH FENNEL', 'Fennel',24),
('FRESH FENNEL (24 HD)', 'Fennel (24 hd)',24),
('GALIA MELON', 'Galia Melon',25),
('GALIA MELON 11 PCS PER BOX', 'Galia Melon',25),
('GALIA MELONS', 'Galia Melon',25),
('GALIA MELONS (11 CT)', 'Galia Melon - 11ct',25),
('GALIA MELON 34#', 'Galia Melon - 34#',25),
('FRESH PEELED GARLIC 5 LB', 'Garlic',null),
('Garlic', 'Garlic',null),
('GARLIC CHOPPED GALLON', 'Garlic Chopped',null),
('GARLIC STEMS/SCAPES', 'Garlic Stem\Scapes',null),
('GARLIC SUPER COLOSSAL', 'Garlic Super Colossal',null),
('FRESH  GINGER  ROOT', 'Ginger',30),
('FRESH GINGER ROOT', 'Ginger',30),
('GRAPEFRUIT', 'Grapefruit',35),
('GRAPEFRUIT 40 LB BOX PINK', 'Grapefruit',35),
('GRAPEFRUIT 40 LB BOX RED', 'Grapefruit',35),
('GRAPEFRUIT PINK', 'Grapefruit',35),
('GRAPEFRUIT RED', 'Grapefruit',35),
('GRAPEFRUIT RED 40 LB BOX', 'Grapefruit',35),
('GRAPEFRUIT 40 LB BOX', 'Grapefruit',35),
('GRAPEFRUIT YELLOW', 'Grapefruit',35),
('GRAPFFIRLIIT PINK', 'Grapefruit - Pink',35),
('GRAPEFRUIT WHITE', 'Grapefruit - White',35),
('GRAPEFRUIT 40 LB BOX * PINK', 'Grapefruit Pink',35),
('GRAPEFRUIT 40 LB BOX * RED', 'Grapefruit Red',35),
('RED GRAPEFRUIT', 'Grapefruit Red',35),
('BLACK SEEDLESS GRAPES (22#)', 'Grapes - Black Seedless',18),
('RED  SEEDLESS  GRAPES  122#\', 'Grapes - Red',18),
('RED SEEDLESS GRAPES (22#)', 'Grapes - Red',18),
('SEEDLESS  VVHITEGRAPES', 'Grapes - White',18),
('SEEDLESS WHITEGRAPES', 'Grapes - White',18),
('RED SEEDLESS GRAPES', 'Grapes Red Seedless',18),
('RED SEEDLESS GRAPES', 'Grapes Red Seedless',18),
('RED SEEDLESS GRAPES 22', 'Grapes Red Seedless',18),
('RED SEEDLESS GRAPES 22#', 'Grapes Red Seedless',18),
('RED.SEEDLESS GRAPES (22#)', 'Grapes Red Seedless',18),
('SEEDLESS WHITEGRAPES 22 LB BOX', 'Grapes White Seedless',18),
('GRAPES WHITE SEEDLESS 22 LBS', 'Grapes White Seedless',18),
('Green Squash', 'Green Squash',20),
('MUSTARD GREENS', 'Greens Mustard',20),
('MUSTARD GREENS 20 LB BOX', 'Greens Mustard',20),
('GUAVA', 'Guava',16),
('GUAVA 10 KGS BOX', 'Guava',16),
('GUAVA 13LB BOX', 'Guava',16),
('GUAVA 16#', 'Guava',16),
('FRESH GUAVA', 'Guava',16),
('HONEY DEW', 'Honeydew',20),
('GOLDEN HONEY DEW MELONS', 'Honeydew Golden',20),
('HC>NEVDEVV  MELONS  20  LBS', 'Honeydew Melons',20),
('HONEYDEW MELONS 20 LB$', 'Honeydew Melons',20),
('HONEYDEW MELONS 20 LBS', 'Honeydew Melons',20),
('FRESH HORSE RADDISH', 'Horse Radish',5),
('FRESH HORSE RADISH', 'Horse Radish',5),
('FRESH HORSERADISH', 'Horseradish',5),
('JACK FRUIT', 'Jack Fruit',15),
('JACK FRUIT 35 LBS BOX', 'Jack Fruit',15),
('WHOLE JACK FRUIT', 'Jack Fruit',15),
('JACKFRUIT', 'Jackfruit',15),
('JACKFRUIT YOUNG SMALL', 'Jackfruit Small',15),
('KALE FRESH', 'Kale Fresh',null),
('FRESH kIWI', 'Kiwi',8),
('FRESH KIWI', 'Kiwi',8),
('FRESH KIWI (10 AVG)', 'Kiwi',8),
('FRESH KIWI (10# AVG)', 'Kiwi',8),
('FRESH KIWI (10#AVG)', 'Kiwi',8),
('FRESH KIWI (104 AVG)', 'Kiwi',8),
('FRESH KIWI (10tt AVG)', 'Kiwi',8),
('KIWI', 'Kiwi',8),
('FRESH KIWI', 'Kiwi',8),
('LEEKS', 'Leeks',18),
('LEEKS 20 LB BOX', 'Leeks',18),
('LEEKS WHITE', 'Leeks',18),
('LEMON  GR.ASS', 'Lemon Grass',null),
('LEMON GRASS', 'Lemon Grass',null),
('LEMON GR.ASS', 'Lemon Grass',null),
('SUNKIST LEMONS', 'Lemon sunkist',35),
('LEMONS', 'Lemons',35),
('LEMONS 40 LBS', 'Lemons',35),
('CELLO WRAPPED ICEBERG LETTUCE', 'Lettece Iceberg',null),
('ICEBERG  LETTUCE', 'Lettuce - Iceberg',40),
('ICEBERG LETTUCE', 'Lettuce - Iceberg',40),
('FRESH ROMAINE LETTUCE', 'Lettuce - Romaine',40),
('BOSTON LETTUCE', 'Lettuce Boston',24),
('BOSTON LETTUCE /BUTTER LETTUCE', 'Lettuce Boston',24),
('BOSTON LETTUCE 24 HEADS', 'Lettuce Boston',24),
('LETTUCE BUTTERCRUNCH', 'Lettuce Butter Crunch',24),
('FRISBEE LETUCE HEAD 2 LB/BX', 'Lettuce Frisee',2),
('FRISEE LETTUCE', 'Lettuce Frisee',2),
('LETTUCE GREEN  LEAF (24HD)', 'Lettuce Green Leaf',20),
('LETTUCE GREEN LEAF (24HD)', 'Lettuce Green leaf',20),
('ICEBERG LETTUCE 45 LB BOX', 'Lettuce Iceberg',40),
('LETTUCE LOLLO BIONDA', 'Lettuce Lollo Bionda',2),
('LOLLO ROSSO LETTUCE 2 LB', 'Lettuce Lollo Rosso',2),
('LETTUCE BOSTON', 'Lettuce Lollo Rosso',2),
('LOLLO ROSSO LETTUCE 2#', 'Lettuce Lollo Rosso',2),
('LOLLO ROSS LETTUCE', 'Lettuce Lollo Rosso',2),
('LOLLO ROSSO LETTUCE 2# BOX', 'Lettuce Lollo Rosso',2),
('LETTUCE LOLLO ROSSO 2LB', 'Lettuce Lollo Rosso',2),
('LETTUCE LOLLO ROSSO 2#', 'Lettuce Lollo Rosso',2),
('LOLLO ROSSO', 'Lettuce Lollo Rosso',2),
('LOLLO ROSSO 2#', 'Lettuce Lollo Rosso',2),
('LOLLO ROSSO 2LB', 'Lettuce Lollo Rosso',2),
('LETTUCE LOLLO ROSSO', 'Lettuce Lollo Rosso',2),
('LETTUCE OAKLEAF', 'Lettuce Oak Leaf',2),
('LETTUCE OAKLEAF (2.5LB/BX)', 'Lettuce Oak Leaf',2),
('OAKLEAF LETTUCE HEAD 2 LB/BX', 'Lettuce Oak Leaf',2),
('LETTUCE OAKLEAF (2.5LBIBX)', 'Lettuce Oak Leaf',2),
('MICRO CUT RAINBOW MIX', 'Lettuce Rainbow Mix',3),
('LETTUCE RED LEAF (24HD)', 'Lettuce red Leaf',20),
('RED LEAF HEAD LETTUCE', 'Lettuce Red Leaf',20),
('BABY RED OAK LETTUCE', 'Lettuce Red oak',2),
('RED OAK  LETTUCE', 'Lettuce Red Oak',2),
('FRESH ROMAINE LETTUCE', 'Lettuce Romaine',40),
('FRESH ROMAINE LETTUCE 40 LB   BOX', 'Lettuce Romaine',40),
('FRESH ROMAINE LETTUCE 40 LB/BX', 'Lettuce Romaine',40),
('FRESH ROMAINE LETTUCE 40 LBIBX', 'Lettuce Romaine',40),
('HEARTS OF ROMAINE', 'Lettuce Romaine',40),
('ROMAINE LETTUCE', 'Lettuce Romaine',40),
('FRESH ROMAINE LETTUCE *5 PCS*', 'Lettuce Romaine 5 hds',1),
('RUCCOLA', 'Lettuce RUCCOLA',3),
('SPRING MIX/MESCULLIN', 'Lettuce Spring Mix',3),
('SPRING MIX LETTUCE', 'Lettuce Spring Mix',3),
('FRESH  LIMES  110#  AVG.)', 'Limes',10),
('FRESH LIMES (10# AVG.)', 'Limes',10),
('MANGOES FRESH 10 LBS', 'Mangoes',10),
('MANGOES FRESH 10 LBS YELLOW', 'Mangoes',10),
('CANARYNELLOW MELON 20#', 'Melon Canary Yellow',null),
('CANARYNELLOW MELON APPROX', 'Melon Canary Yellow',null),
('DINO MELON', 'Melon Dino',null),
('GALIA MELONS RIPE', 'Melon Galia',25),
('GALIA MELON 6 CT', 'Melon Galia',25),
('GALIA MELON APPROX 25#', 'Melon Galia 25 lb',25),
('MELORENGE MELON', 'Melon Melorenge',null),
('FRESH MINT', 'Mint',2.2),
('BUTTON MUSHROOMS 10 LB BOX', 'Mushroom Button',10),
('SHITAKE MUSHROOM 3 LB', 'Mushroom Shiitake',3),
('FRESH  MUSHROOMS', 'Mushrooms',10),
('FRESH MUSHROOMS', 'Mushrooms',10),
('FRESH MUSHROOMS 10 LB BOX', 'Mushrooms',10),
('FRESH MUSTARD LEAVES', 'Mustard',null),
('NECTARINES', 'Nectaries',25),
('NECTARINES 28 LB BOX', 'Nectarine',25),
('NECTARINES 25 LB BOX', 'Nectarines',25),
('FRESH  OKRA  15   LBS', 'Okra',15),
('FRESH OKRA 15 LBS', 'Okra',15),
('FRESH OKRA 16 LBS', 'Okra',15),
('Okra', 'Okra',15),
('CHINESE OKRA', 'Okra Chinese',15),
('INDIAN OKRA', 'Okra Indian',15),
('DRY YELLOW ONIONS MED.', 'Onion',50),
('WHITE PEARL ONION', 'Onion Pearl White',25),
('RED ONIONS 25 LB BOX', 'Onion Red',25),
('RED ONIONS LARGE SIZE', 'Onion Red Large',25),
('SHALLOT 10#', 'Onion Shallot',10),
('SHALLOT ONION, 10#', 'Onion Shallots',10),
('LARGE SPANISH ONION', 'Onion Spanish Large',50),
('LARGE SPANISH ONION 50 LB', 'Onion Spanish Large',50),
('DRY WHITE ONIONS', 'Onion White',50),
('WHITE PEARL ONION 25 LB BOX', 'Onion White Pearls',25),
('DRY YELLOW ONIONS 50LBS MEDIUM', 'Onion Yellow',50),
('DRY YELLOW ONIONS LARGE', 'Onion Yellow',50),
('DRY YELLOW ONIONS SIZE', 'Onion Yellow',50),
('RED ONIONS', 'Onions - Red',25),
('DRY  VELLOVV  ONIONS', 'Onions - Yellow',50),
('DRY YELLOW ONIONS', 'Onions - Yellow',50),
('DRY YELLOW ONIONS 50 LB', 'Onions - Yellow',50),
('RED ONIONS LARGE', 'Onions Red Large',25),
('DRY YELLOW ONIONS 50LBS', 'Onions yellow',50),
('ORANGES  40 LBS', 'Orange',35),
('ORANGES 40 LBS', 'Orange',35),
('FRESH ORANGE', 'Orange',35),
('ORANGES 40 LBS NAVEL', 'Orange Navel',35),
('SUNKIST ORANGE(88ct) VALENCIA', 'Orange Sunkist 88',35),
('SUNKIST ORANGE', 'Orange Sunkist',35),
('SUNKIST ORANGE 88L0 40 LB BOX', 'Orange Sunkist',35),
('SUNKIST ORANGE(880', 'Orange SUNKIST',35),
('SUNKIST ORANGE(88ct) 40 LB BOX', 'Orange Sunkist',35),
('SUNKIST ORANGE 88ct', 'Orange Sunkist 88',35),
('SUNKIST ORANGE(88ct)', 'Orange Sunkist 88',35),
('ORANGES  SOCT  40  LBS', 'Oranges',35),
('ORANGES  SOCT  4-0LEIS', 'Oranges',35),
('ORANGES 80 CT 40 LBS', 'Oranges',35),
('FRESH OREGANO BUNCH', 'OREGANO',2.2),
('FRESH PAPAYA', 'Papaya',10),
('FRESH PAPAYA  10# AVG', 'Papaya',10),
('FRESH PAPAYA (10# AVG)', 'Papaya',10),
('FRESH PAPAYA (10# AVG) RIPE', 'Papaya',10),
('FRESH PAPAYA (100 AVG)', 'Papaya',10),
('FRESH PAPAYA(10# AVG)HALF-RIPE', 'Papaya',10),
('FRESH PAPAYA110# AVG)', 'Papaya',10),
('FRESHPAPAYA(10# AVG)10 PER CS NOT RIPE', 'Papaya',10),
('FRESH COOKING PAPAYA (40#)', 'Papaya Cooking',10),
('PARSLEY', 'Parsley',2),
('PARSLEY CURLY', 'Parsley',2),
('PARSLEY * CURLY', 'Parsley - Curley',2),
('PARSLEY CURLEY', 'Parsley Curley',2),
('PARSLEY * CURLEY', 'Parsley Curly',2),
('PARSLEY FLAT ITALIAN', 'Parsley Flat Italian',2),
('PARSNIPS', 'Parsnips',20),
('PARSNIPS(20#AVG)', 'Parsnips',20),
('PEACHES', 'Peaches',25),
('PEACHES 25 LBS', 'Peaches',25),
('PEACHES25 LBS', 'Peaches',25),
('BOSC STEWING PEARS', 'Pear Bosc',40),
('CHINESE PEAR 30# BOX', 'Pear Chinese',40),
('JAPANESE PEAR 40 LB BOX', 'Pear Japanese',40),
('pears', 'Pears',40),
('PEARS  4-0LBS', 'Pears',40),
('PEARS 40 LBS', 'Pears',40),
('PEARS 40 LBS', 'Pears',40),
('PEARS 40 LBS', 'Pears',40),
('PEARS 40 LBS (HALF RIPE)', 'Pears',40),
('PEARS 40 LBS GREEN', 'Pears',40),
('PEARS40  LBS', 'Pears',40),
('PEARS 40 LB', 'Pears',40),
('PEARS 40 LBS GREN RIPE', 'Pears Green',40),
('YELLOW PEARS 40 LBS', 'Pears Yellow',40),
('HOT  CHILI  PEPPERS', 'Pepper - Chili',25),
('HOT CHILI PEPPERS', 'Pepper - Chili',25),
('HOT CHILI PEPPERS GREEN', 'Pepper - Chili Green',25),
('RED HOT CHILI PEPPERS', 'Pepper - Chili Red',25),
('GREEN  BELL  PEPPERS', 'Pepper - Green Bell',25),
('GREEN BELL PEPPERS', 'Pepper - Green Bell',25),
('JALAPENO  PEPPERS', 'Pepper - Jalapeno',25),
('JALAPENO PEPPERS *GREEN*', 'Pepper - Jalapeno',25),
('RED BELL PEPPER', 'Pepper - Red Bell',25),
('YELLOW BELL PEPPER', 'Pepper - Yellow',25),
('YELLOW PEPPER', 'Pepper - Yellow',25),
('BIRDSEYE CHILI', 'Pepper Birdseye',25),
('CAYENNE PEPPER', 'Pepper Cayenne',25),
('FRESH CAYENNE PEPPER', 'Pepper Cayenne',25),
('CAYENNE PEPPER GREEN', 'Pepper Cayenne Green',25),
('GREEN CAYENNE PEPPERS', 'Pepper Cayenne Green',25),
('BIRD''S EYE CHILI', 'Pepper Chili Birds Eye',25),
('HOT CHILI PEPPERS GREEEN', 'Pepper Chili Green',25),
('HOT CHILI PEPPERS GREEN SMALL', 'Pepper Chili Green',25),
('HOT CHILI PEPPERS SMALL GREEN', 'Pepper Chili Green',25),
('Chili Peppers Green', 'Pepper Chili Green',25),
('HOT CHILI PEPPERS * RED', 'Pepper Chili Red',25),
('HOT CHILI PEPPERS JALAPENO', 'Pepper Chili Red',25),
('HOT CHILI PEPPERS RED', 'Pepper Chili Red',25),
('GREEN BELL PEPPERS 25 LB BOX', 'Pepper Green',25),
('Green Peppers', 'Pepper Green',25),
('LONG HOT CHILI PEPPERS SPANISH', 'Pepper Green Long Hot',25),
('HOT CHILI PEPPERS GREEN PADI', 'Pepper Green Pad Thia hot',25),
('JALAPENO', 'Pepper Jalapeno',25),
('JALAPENO CHILI PEPPERS', 'Pepper Jalapeno',25),
('JALEPENO PEPPERS', 'Pepper Jalapeno',25),
('Jalapeno Pepper', 'Pepper Jalapeno',25),
('GREEN JALAPENO PEPPERS', 'Pepper Jalapeno Green',25),
('RED JALAPENO PEPPERS', 'Pepper Jalapeno Red',25),
('LONG CHILI PEPPERS', 'Pepper Long Chili',25),
('LONG HOT CHILI PEPPERS', 'Pepper Long Hot Chili',25),
('POBLANO CHILI PEPPERS', 'Pepper Poblano',25),
('Red Peppers', 'Pepper Red',25),
('JALAPENO RED HOT CHILI PEPPERS', 'Pepper Red Chili',25),
('RED HOT CHILI PEPPERS LONG', 'Pepper Red Chili Long',25),
('RED HOT CHILI PEPPERS SMALL', 'Pepper Red Chili Small',25),
('LONG RED HOT CHILI PEPPERS', 'Pepper Red Long Hot',25),
('RED HOT CHILI PEPPERS THAI', 'Pepper Red Thai Hot',25),
('THAI HOT CHILI/PEPPERS', 'Pepper Thai Hot',25),
('THAI CHILI//PEPPER', 'Pepper Thai Red',25),
('THAILAND RED CHILI PEPPERS', 'Pepper Thai Red',25),
('CHILLI PADI GREEN', 'Pepper, Padi Green',25),
('HOT CHILI PEPPERS CAYENNE', 'Peppers Cayenne',25),
('HOT CHILI PEPPERS GREEN Cayenne', 'Peppers Cayenne',25),
('PIMIENTO (RED CHERRY PEPPER)', 'Peppers Cherry Red',25),
('XTRA HOT CHILI PEPPERS', 'Peppers Chili Extra Hot',25),
('HOT CHILI PEPPERS GREN', 'Peppers Chili Green',25),
('HOT CHILI PEPPERS GREEN LARGE', 'Peppers Chili Green Large',25),
('RED HOT CHILI PEPPERS JALAPENO', 'Peppers Chili Hot Jalapeno',25),
('HOT CHILI PEPPER SPANISH GREEN', 'Peppers Chili Spanish Green',25),
('EXTRA HOT CHILI PEPPERS', 'Peppers Chili Xhot',25),
('HOT CHILI PEPPERS XHOT', 'Peppers Chili Xhot',25),
('PEPPERS CUBANELLE', 'Peppers Cubanelle',25),
('GREENBELL PEPPERS', 'Peppers Green Bell',25),
('GREEN BELL PEPPERS * LARGE FOR STUFFING', 'Peppers Green Large',25),
('JALAPENO PEPPERS', 'Peppers Jalapeno',25),
('XTR HOT CHILI PEPPERS', 'Peppers XHOT Chili',25),
('Yellow Peppers', 'Peppers Yellow',25),
('FRESH PINEAPPLE 20 LB BOX', 'Pineapple',25),
('FRESH PINEAPPLE GOLD', 'Pineapple',25),
('FRESH PINEAPPLE (6CT)', 'Pineapple 6 count',25),
('FRESH PINEAPPLE** DOLE BRAND', 'Pineapple Dole only',25),
('FRESH PINEAPPLE', 'Pineapples',25),
('FRESH PINEAPPLE', 'Pineapples',25),
('FRESH PINEAPPLE ''DOLE""', 'Pineapples',25),
('FRESH PINEAPPLE (6 CT)', 'Pineapples',25),
('FRESH PINEAPPLE 6 CT', 'Pineapples',25),
('Pineapples', 'Pineapples',25),
('PLANTAIN COOKING BANANA 45 LB', 'Plantains',45),
('PLANTAIN COOKING BANANA 45 LB', 'Plantains',45),
('PLANTAIN COOKING BANANA', 'Plantains',45),
('PLANTAINS', 'Plantains',45),
('Plum', 'Plum',28),
('PLUMS', 'Plums',28),
('PLUMS .', 'Plums',28),
('PLUMS 28 LB BOX', 'Plums',28),
('POMEGRANATE', 'Pomegranate',null),
('POMELO (35 - 40 LBS BOX)', 'Pomelo',40),
('BABY POTATOES 50 LB', 'Potato Baby',50),
('BABY YELLOW POTATOES', 'Potato Baby Yellow',50),
('RUSSET BAKING POTATOES 50 LB', 'Potato Baking Russet',50),
('IDAHO BAKING POTATOES 50 LB/BG', 'Potato Idaho',50),
('RED POTATOES', 'Potato Red',50),
('RED POTATOES 50 LB', 'Potato Red',50),
('RED POTATOES 50 LB BAG', 'Potato Red',50),
('BABY RED YUKON POTATO', 'Potato Red Baby',50),
('SMALL RED POTATO 50#', 'Potato Small Red C from store',50),
('SWEET POTATOES 40 LB BOX', 'Potato Sweet',40),
('SWEET POTATOES 40 LB BOX * PURPLE', 'Potato Sweet Purple',40),
('NEW WHITE POTATOES 50 LB BAG', 'Potato White',50),
('NEW WHITE POTATOES 50LBS', 'Potato White',50),
('NEW WHITE POTATOES 50LBS LARGE', 'Potato White',50),
('WHITE POTATOES', 'Potato White',50),
('LARGE SIZE YELLOW POTATO, 50#', 'Potato Yukon',50),
('YELLOW POTATOS/YUKON POTATO', 'Potato Yukon',50),
('IDAHO BAKING POTATOES', 'Potatoes - Idaho',50),
('SVVEET  POTATOES', 'Potatoes - Sweet',40),
('SWEET POTATOES', 'Potatoes - Sweet',40),
('NEVV  VVHITE  POTATOES', 'Potatoes - White',50),
('NEVV  WHITE  POTATOES', 'Potatoes - White',50),
('NEW WHITE POTATOES', 'Potatoes - White',50),
('NEW WHITE POTATOES 50 LB', 'Potatoes - White',50),
('NEW WHITE POTATOES  LARGE', 'Potatoes - White Large',50),
('NEW WHITE POTATOES LARGE', 'Potatoes - White Large',50),
('PUMPKINS 40 LB BOX YELLOW', 'Pumpkin',40),
('PUMPKINS 40 LB BOX', 'Pumpkin',40),
('PUMPKINS  VVHITE', 'Pumpkin - White',40),
('PUMPKINS WHITE', 'Pumpkin - White',40),
('PUMPKINS 40 LB BOX GREEN', 'Pumpkin Green',40),
('PUMPKINS 40 LB BOX * RED', 'Pumpkin Red',40),
('PUMPKINS 40 LB BOX RED', 'Pumpkin Red',40),
('PUMPKINS RED', 'Pumpkin Red Acorn',40),
('PUMPKINS SMALL', 'Pumpkin Small',40),
('PUMPKINS 40 LB BOX ** WHITE', 'Pumpkin White',40),
('PUMPKINS 40 LB BOX WHITE', 'Pumpkin White',40),
('PUMPKINS 40 LB BOX * YELLOW', 'Pumpkin Yellow',40),
('PUMPKINS YELLOW', 'Pumpkin Yellow',40),
('PUMPKINS YELLOW 40 LB BOX', 'Pumpkin Yellow',40),
('PUMPKINS', 'Pumpkins',40),
('PUMPKINS', 'Pumpkins',40),
('LETTUCE RADICCHO 10#', 'Radicchio',10),
('RED RADISHES 6 OZ BAGS', 'Radish - Red',30),
('RED RADISHES 6 02 BAGS', 'Red Radishes',30),
('Red Radish', 'Red Radishes',30),
('RIDGE GOURD', 'Ridge Gourd',30),
('RIDGE GOURD 1 CHINESE OKRA 30#', 'Ridge Gourd',30),
('HEARTS OF ROMAINE (12/3PKT)', 'Romaine Hearts',null),
('Iceberg sub Romaine', 'Romaine Lettuce',40),
('FRESH ROSEMARY BUNCH', 'Rosemary',2.5),
('FRESH ROSEMARY', 'Rosemary',2.5),
('FRESH ROSMARY', 'Rosemary',2.5),
('RUCOLA LETTUCE', 'Rucola Baby Arrugula',null),
('WINTER/SAVOY CABBAGE', 'Savoy Cabbage',35),
('SCULLIC>NfSPR.ING  ONION)  1/3  LBS', 'Scallion Onions',48),
('SCULLIC>NtSPR.ING  ONION\   ''1/3  LBS"', 'Scallion Onions',48),
('SCULLION(SPRING ONION) 1/3 LBS', 'Scallion Onions',48),
('SCULLION(SPRING ONION) 113 LBS', 'Scallion Onions',48),
('SCULLION SPRING ONION', 'Scallions',48),
('SCULLION SPRING ONION)', 'Scallions',48),
('SCULLION SPRING ONION) 1/3 LBS', 'Scallions',48),
('SCULLION(SPRING ONION)', 'Scallions',48),
('SCULLION(SPRING ONION) 1 13 LBS', 'Scallions',48),
('SCULLION(SPRING ONION) 1/3 LBS', 'Scallions',48),
('SCULLION(SPRING ONION) 113 Las', 'Scallions',48),
('SCULLION1SPRING ONION) 1/3 LBS', 'Scallions',48),
('SCULLIONISPRING ONION) 1/3 LBS', 'Scallions',48),
('Scullions', 'Scallions',48),
('SCULLIQN(SPRING ONION) 1/3 LBS', 'Scallions',48),
('SCULLION(SPRING ONIO', 'Scallions',48),
('SPRING ONIONS', 'Scallions',48),
('SHALLOTS, NON PEELED', 'Shallot , Non Peeled',10),
('SNAKE GOURD', 'Snake Gourd',30),
('FRESH SNOW PEA', 'Sno Pea',10),
('FRESH SNOW PEA (10#_AVG)', 'Sno Pea',10),
('FRESH SNOW PEA (100 AVG)', 'Sno Peas',10),
('FRESH SNOW PEA (10# AVG)', 'Snow Pea',10),
('BABY SPINACH LEAVES (412.5LB)', 'Spinach',10),
('FRESH  SPINACH', 'Spinach',10),
('FRESH SPINACH', 'Spinach',10),
('FRESH SPINACH 10 LB BOX', 'Spinach',10),
('FRESH SPINACH 25 LB BOX', 'Spinach',10),
('FRESH CELLO SPINACH 12 LB BOX', 'Spinach',10),
('Spinach', 'Spinach',10),
('FRESH BABY SPINACH', 'Spinach Baby',10),
('FRESH SPINACH BABY', 'Spinach Baby',10),
('BABY SPINACH', 'Spinach Baby  3 lb box',10),
('FRESH SPINACH BABY CLEANED', 'Spinach Baby Cleaned 2.5 lb bag',10),
('FRESH CELLO SPINACH', 'Spinach Cello',10),
('SPONGE GOURD', 'Sponge Gourd',30),
('SPRING MIX 3LBS CASE', 'Spring Mix',3),
('SPRING MIXIMESCULLIN 3LB', 'Spring mix',3),
('SPRING MIX 3 LB BAG', 'Spring Mix',3),
('MICRO CUT RAINBOW MIX 80Z', 'Spring Mix Rainbow Micro',3),
('BUTTERNUT SQUASH', 'Squash',20),
('ACORN SQUASH', 'Squash Acorn',40),
('ACORN SQUASH 45 LB BOX', 'Squash Acorn',40),
('ACORN SQUASH (RED PUMPKIN)', 'Squash Acorn Red Pumpkin',40),
('BUTTERNUT SQUASH 45 LB BOX WHITE LONG', 'Squash Butternut',40),
('BUTTERNUT SQUASH YELLOW LONG', 'Squash Butternut',40),
('BUTTERNUT YELOW SQUASH', 'Squash Butternut',40),
('BUTTERNUT SQUASH GREEN', 'Squash Butternut Green',40),
('BUTTERNUT SQUASH(WHITE PUMPKIN', 'Squash Butternut White Pumpkin',40),
('BUTTERNUT SQUASH YELLOW', 'Squash Butternut Yellow',40),
('CALABASSA SQUASH', 'Squash Calabassa',40),
('ZUCCHINI SQUASH 22 LB BOX', 'Squash Green',20),
('LONG WHITE SQUASH', 'Squash Long White',20),
('PUMPKIN SQUASH', 'Squash Pumpkin',40),
('RED SQUASH 45 LB BOX', 'Squash Red',20),
('YELLOW SQUASH', 'Squash Yellow',20),
('YELLOW SQUASH 22 LB BOX', 'Squash Yellow',20),
('ZUCCHINI SQUASH WHITE', 'Squash Yellow',20),
('YELLOW SQUASH LONG NECK', 'Squash Yellow Zucchini',20),
('STRAWBERRIES (12 PIS) 12 LB BX', 'Strawberries',8),
('STRAWBERRIES (12 PTS) 12 LB BX', 'Strawberries',8),
('STRAWBERRIES 12 PTS)', 'Strawberries',8),
('STRAWBERRIES 8 LB CASE', 'Strawberries',8),
('STRAWBERRIES NIA', 'Strawberries',8),
('STRAWBERRIES (12 PIS)', 'Strawberries',8),
('STRAWBERRIES  (12 PTS)', 'Strawberries',8),
('STRAWBERRIES (12 PTS)', 'Strawberries',8),
('STRAWBERRY N/A', 'Strawberries',8),
('STRAWBERRIES 8 LB BX', 'Strawberries',8),
('STRING  BEANS', 'String Beans',25),
('STRING BEANS', 'String Beans',25),
('STRING BEANS 25 LB BOX', 'String Beans',25),
('STRING BEANS 26 LB BOX', 'String Beans',25),
('SUNKIST ORANGE(88ct) 40 LB BOX * VALENCIA', 'Sunkist Orange Valencia',35),
('TANGERINES (MANDARIN ES NIA)', 'Tangerine Mandarin',30),
('TANGERINES', 'Tangerines',30),
('TANGERINES 40 LB BOX', 'Tangerines',30),
('TANGERINES ( MANDARINES  N/A)', 'Tangerines - Mandarin',30),
('TANGERINES (MANDARINES N/A)', 'Tangerines - Mandarin',30),
('FRESH TARO ROOT', 'Taro Root',35),
('FRESH THYME', 'Thyme',2.5),
('FRESH THYMES 1KG', 'Thyme',2.5),
('THYME FRESH', 'Thyme',2.5),
('FRESH THYME 2.2#', 'Thyme 2.2 lb',2.5),
('FRESH THYME BUNCH', 'Thyme Fresh Bunch',2.5),
('TOMATOES *UNRIPE* 25 LB BOX', 'Tomato',25),
('TOMATOES 1(2 RIPE', 'Tomato',25),
('TOMATOES 1/2 RIPE 25 LB BOX', 'Tomato',25),
('TOMATOES 1/2 RIPE BEEFSTEAK', 'Tomato',25),
('TOMATOES 112 RIPE', 'Tomato',25),
('TOMATOES 112 RIPE 25 LB BOX', 'Tomato',25),
('TOMATOES 25 LB BOX', 'Tomato',25),
('TOMATOES BACKWARDS 1/2 RIPE', 'Tomato',25),
('TOMATOES RIPE 25 LB BOX', 'Tomato',25),
('TOMATOES RED 25 LB BOX', 'Tomato',25),
('CHERRY TOMATOES (12/PINTS)', 'Tomato - Cherry',12),
('BEEF STEAK TOMATOES', 'Tomato Beef Stake',25),
('TOMATO BEEFSTEAK', 'Tomato Beefstake',25),
('TOMATOES BEEFSTAKE', 'Tomato Beefstake',25),
('Cherry Tomato', 'Tomato Cherry',12),
('CHERRY TOMATOES', 'Tomato Cherry',12),
('CHERRY TOMATOES (121PINTS)', 'Tomato Cherry',12),
('CHERRY TOMATOES 12/PINTS', 'Tomato Cherry',12),
('ROMA TOMATOES', 'Tomato Plum',25),
('TOMATO PLUM ROMANO RED', 'Tomato Plum',25),
('TOMATOES RED', 'Tomato Red',25),
('TOMATOES 112 RIPE RED', 'Tomato RIPE',25),
('TOMATOES', 'Tomatoe',25),
('TOMATOES   ''1/2  RIPE"', 'Tomatoes',25),
('TOMATOES  1/2  RIPE', 'Tomatoes',25),
('TOMATOES *FULL* RIPE', 'Tomatoes',25),
('TOMATOES 1/2 RIPE', 'Tomatoes',25),
('TOMATOES BACKWARD', 'Tomatoes',25),
('CHERRYTOMATOES (421PINTS)', 'Tomatoes Cherry',12),
('TOMATOES ON THE VINE', 'Tomatoes on the Vine',25),
('YELLOW TURNIPS', 'Turnip Yellow Rutabaga',40),
('WHITE TURNIPS', 'Turnips - White',25),
('yELLOW TURNIPS 50 LB BOX', 'Turnips Yellow',40),
('Watermellon', 'Watermelon',40),
('VVATER.MELONS', 'Watermelons',40),
('VVATERMELC>NS', 'Watermelons',40),
('Watermelon', 'Watermelons',40),
('WATERMELONS', 'Watermelons',40),
('WATERMELONS SWEET RED', 'Watermelons',40),
('WAX BEANS/YELLOW BEANS', 'Wax Beans',null),
('WHITE TURNIPS 20 LB BOX', 'White Turnips',25),
('WINTER GOURD', 'Winter Gourd',30),
('YELLOW LONG', 'Yellow Long',null),
('YELLOW SQUASH STRAIGHT NECK', 'Yellow Squash',20),
('YELLOW SQUASH 45 LB BOX', 'Yellow Squash',20),
('ZUCCHINI SQUASH', 'Zucchini Squash',20),
('.ZUCCHINI  SQUASH', 'Zucchini Squash',20),
('ZUCCHINI  SQUASH', 'Zucchini Squash',20),
('ZUCCHINI SQUASH', 'Zucchini Squash',20),
('ZUCCHINI SQUASH 22 LB BOX', 'Zucchini Squash',20),
('ZUCCHINI SQUASH GREEN', 'Zucchini Squash',20)