DROP TABLE IF EXISTS name_clean_up CASCADE;

CREATE TABLE name_clean_up (
	item_id serial PRIMARY KEY,
	order_name varchar(100),
	sticker_name varchar(100)
);

INSERT INTO name_clean_up (order_name, sticker_name)
VALUES ('ACORN SQUASH RED', 'Acorn Squash'), 
('BRAEBURN APPLE', 'Apple - Braeburn'), 
('APPLES GOLDEN DELICIOUS', 'Apple - Golden'), 
('GRANNY SMITH APPLES', 'Apple - Granny Smith'), 
('GREEN  APPLES', 'Apple - Green'), 
('GREEN APPLES', 'Apple - Green'), 
('MACINTOSH  APPLES', 'Apple - Macintosh'), 
('MACINTOSH APPLES', 'Apple - Macintosh'), 
('APPLES  RED  DELICIOUS  4-0LBS', 'Apple - Red Delicious'), 
('APPLES RED DELICIOUS 40 LBS', 'Apple - Red Delicious'), 
('BRAEBURN APPLE 40 LB BOX', 'Apple - Braeburn'), 
('FUJI APPLE', 'Apple - Fuji'), 
('FUJI APPLES 40 LBS', 'Apple - Fuji'), 
('APPLES  GOLDEN DELICIOUS', 'Apple - Golden Delicious'), 
('APPLES GOLDEN CRUNCHY DELICIOUS 40 LB', 'Apple - Golden Delicious'), 
('APPLES GOLDEN DELICIOUS 40 LB BOX', 'Apple - Golden Delicious'), 
('1GRAPP', 'Apple - Granny Smith'), 
('Granny Smith Apple', 'Apple - Granny Smith'), 
('GRANNY SMITH APPLES 40 LB BOX', 'Apple - Granny Smith'), 
('Green Apple', 'Apple - Green'), 
('GREEN APPLES 40 LB', 'Apple - Green'), 
('GREEN APPLES 40 LB BOX', 'Apple - Green'), 
('JONAGOLD APPLE 46#', 'Apple - Jonagold'), 
('MACINTOSH APPLES 40  LB BOX', 'Apple - Macintosh'), 
('MACINTOSH APPLES 40 LB BOX', 'Apple - Macintosh'), 
('APPLES RED DELICIOUS 40 LB_S', 'Apple - Red Delicious'), 
('YELLOW APPLE', 'Apple - Yellow'), 
('APPLES GOLDEN DELICIOUS 40 LB', 'Apples - Golden'), 
('HONEY CRISPS APPLES 40 LBS', 'Apples - Honeycrisp'), 
('APPLES RED DELICIOUS', 'Apples - Red Delicious'), 
('FRESH APRICOTS 24 LBS', 'Apricots'), 
('FRESH ARTICHOKE 20 LB BOX', 'Artichoke'), 
('ARUGULA', 'Arugula'), 
('FRESH ARUGULA 4LB BOX', 'Arugula - 4 lb box'), 
('ROCKET SALAD/ARUGULA 3#', 'Arugula Baby'), 
('ASIAN PEARS (APPROX 40#)', 'Asian Pears (approx 40#)'), 
('ASPARAGUS', 'Asparagus'), 
('FRESH ASPARAGUS', 'Asparagus'), 
('FRESH ASPARAGUS 11 LB BOX', 'Asparagus'), 
('FRESH AVOCADO (20#)', 'Avocado'), 
('FRESH AVOCADO (20#} HALF RIPE', 'Avocado'), 
('HAAS AVOCADO', 'Avocado'), 
('FRESH AVOCADO (10# BX', 'Avocado'), 
('FRESH AVOCADO (10# BX)', 'Avocado'), 
('FRESH AVOCADO (10# BX) NOT RIPE', 'Avocado'), 
('FRESH AVOCADO (20#', 'Avocado'), 
('FRESH AVOCADO (20)', 'Avocado'), 
('ARUGULA 8 OZ', 'Baby Arugula'), 
('RUCOLLA 3#', 'Baby Arugula'), 
('ARUGALA', 'Baby Arugula (3.5 lb/box)'), 
('ARUGULA (3 POUND/BOX)', 'Baby Arugula (3.5 lb/box)'), 
('BABY ARUGULA (3.5 LB/BOX)', 'Baby Arugula (3.5 lb/box)'), 
('ROCKET SALAD BABY ARUGA;A', 'Baby Arugula (3.5 lb/box)'), 
('PITCHAY', 'Baby Bok Choy'), 
('FRESH BABY SPINACH CLEANED', 'Baby Spinach'), 
('Banana', 'Banana'), 
('BANANAS GREEN 40 LB BOX', 'Banana'), 
('BANANAS GREEN 40 LB/BX', 'Banana'), 
('BANANAS HALF RIPE 40 LB BOX', 'Banana'), 
('BANANAS RIPE 40 LB BOX', 'Banana '), 
('PLANTAIN COOKING BANANA 45 LB', 'Banana - Plaintain'), 
('BANANAS', 'Banana'), 
('BANANAS  HALF  RIPE', 'Banana'), 
('BANANAS HALF RIPE', 'Banana'), 
('BANANAS HALF RIPE GREEN', 'Banana'), 
('BANANAS RIPE', 'Banana'), 
('BANANAS GREEN', 'Banana - Green'), 
('BANANAS HALF RIPE ', 'Banana - Half Ripe'), 
('FRESH BASIL 2.5 LB  BAG           *CANNOT BRK BAG OF 1.14kg.*', 'Basil'), 
('FRESH BASIL 2.5 LB BAG', 'Basil'), 
('FRESH BASIL 2.6 LB BAG', 'Basil'), 
('LIMA BROAD BEAN', 'Bean - Lima Broad'), 
('LONG BEANS', 'Bean - Long'), 
('SNAP BEAN SITAO PEA', 'Bean - Snap Sitao Pea'), 
('BEAN  SPROUTS', 'Bean Sprouts'), 
('BEAN SPROUTS', 'Bean Sprouts'), 
('BEAN SPROUTS 10 LB BX', 'Bean Sprouts'), 
('WAX BEANS / YELLOW BEANS', 'Beans Wax'), 
('BEET ROOT', 'Beet Root'), 
('BEET ROOT 25 LB BOX', 'Beet Root'), 
('BEET ROOT LARGE', 'Beet Root'), 
('BITTER MELON/GOURD', 'Bitter Melon/Gourd'), 
('BITTER MELON1GOURD', 'Bitter Melon/Gourd'), 
('BITTER MELONIGOURD', 'Bitter Melon/Gourd'), 
('BLUEBERRIES  (12 PTS)', 'Blueberries'), 
('BLUEBERRIES (12 PTS)', 'Blueberries'), 
('BOC   CHOI  FR.ESH', 'Bok Choy'), 
('BOC   CHOI  FRESH', 'Bok Choy'), 
('BOC CHOI', 'Bok Choy'), 
('BOC CHOI FRESH', 'Bok Choy'), 
('BOC CHOI FRESH 40 LB BOX', 'Bok Choy'), 
('BOO CHOI FRESH', 'Bok Choy'), 
('BOC CHOI ', 'Bok Choy'), 
('BABY BOC CHOI FRESH (SMALL)', 'Bok Choy Baby'), 
('BABY BOC CHOY 30#', 'Bok Choy Baby'), 
('SMALL BOC CHOI FRESH', 'Bok Choy Baby'), 
('BOTTLE GOURD', 'Bottle Gourd'), 
('BROCCOLI', 'Broccoli'), 
('FRESH  BROCCOLI', 'Broccoli'), 
('FRESH BROCCOLI', 'Broccoli'), 
('FRESH BROCCOLI 22 LB BOX', 'Broccoli'), 
('BRUSSEL SPROUTS', 'Brussels Sprouts'), 
('BRUSSEL SPROUTS 25 LB BOX', 'Brussels Sprouts'), 
('RED BUTTERNUT SQUASH', 'Butternut Squash - Red '), 
('BUTTERNUT SQUASH 45 LB BOX', 'Butternut Squash'), 
('BUTTERNUT SQUASH WHITE', 'Butternut Squash - White'), 
('CHINESE  CABBAGE', 'Cabbage - Chinese'), 
('CHINESE CABBAGE', 'Cabbage - Chinese'), 
('RED CABBAGE', 'Cabbage - Red'), 
('VVHITE  CABBAGE', 'Cabbage - White'), 
('WHITE CABBAGE', 'Cabbage - White'), 
('NAPPA CABBAGE 40 LB BOX', 'Cabbage - Napa'), 
('CHINESE CABBAGE 40 LB BOX', 'Cabbage - Chinese Napa'), 
('GREEN CABBAGE', 'Cabbage - Green'), 
('GREEN CABBAGE 50 LB BOX', 'Cabbage - Green'), 
('NAPPA CABBAGE', 'Cabbage - Napa'), 
('PURPLE CABBAGE', 'Cabbage - Purple'), 
('RED CABBAGE 50 LB BOX', 'Cabbage - Red'), 
('CABBAGE SAVOY', 'Cabbage - Savoy'), 
('SAVOY CABBAGE', 'Cabbage - Savoy'), 
('WHITE CABBAGE "SAVOY"', 'Cabbage - Savoy'), 
('WHITE CABBAGE SHREDDED', 'Cabbage - shredded'), 
('WHITE CABBAGE 50 LB BOX', 'Cabbage - White'), 
('WHITE CABBAGE 60 LB BOX', 'Cabbage - White'), 
('CANTALOUPES', 'Cantaloupe'), 
('CANTALOUPES 40 LB BOX', 'Cantaloupe'), 
('BABY CARROTS', 'Carrot - Baby'), 
('CARROTS TOPPED 50 LB BAG', 'Carrot - Loose'), 
('CARROTS TOPPED MEDIUM SIZE', 'Carrot - Med'), 
('CAR.ROTS  TOPPED', 'Carrot'), 
('CARROTS  TOPPED', 'Carrot'), 
('CARROTS TOPPED', 'Carrot'), 
('CARROTS TOPPED 50 LB', 'Carrot'), 
('CARROTS TOPPED 60 LB BAG', 'Carrot'), 
('CASSAVA', 'Cassava'), 
('CASSAVA ROOT', 'Cassava Root'), 
('FRESH CASSAVA', 'Cassava Root'), 
('CAULIFLC>VVER  TRIM  VVRAP', 'Cauliflower'), 
('CAULIFLOVVER   TRIM  VVRAP', 'Cauliflower'), 
('CAULIFLOVVER  TRIM  VVRAP', 'Cauliflower'), 
('CAULIFLOWER TRIM WRAP', 'Cauliflower'), 
('CAULIFLOWER TRIM WRAP 20 LB', 'Cauliflower'), 
('CAULIFLOWER TRIM WRAP 20 LB   BOX', 'Cauliflower'), 
('CAULIFLOWER TRIM WRAP 20 LB/BX', 'Cauliflower'), 
('CELERY', 'Celery'), 
('CELERY 50 LB BAG', 'Celery'), 
('CELERY ROOT', 'Celery Root'), 
('FR.ESH  CHAYOTE', 'Chayote'), 
('FRESH CHAYOTE', 'Chayote'), 
('FRESH CHAYOTE 10 LB BOX', 'Chayote'), 
('CHERRIES', 'Cherries'), 
('CHERRIES 18 LB BOX', 'Cherries'), 
('CHERRY TOMATOES 12 LB/BX', 'Cherry Tomato'), 
('CHICORY 22#/BX', 'Chicory'), 
('HOT CHILI PEPPERS ex hot', 'Chili Peppers ex hot red'), 
('CHIVES', 'Chives'), 
('CHIVES 2.2# BOX', 'Chives'), 
('FRESH CHIVES', 'Chives'), 
('FRESH CHIVES 2# BOX', 'Chives'), 
('FRESH CHIVES BUNCH', 'Chives'), 
('FRESH CLEMENTINES 5 LB', 'Clementines'), 
('FRESH COCONUTS', 'Coconuts'), 
('FRESH COCONUTS (OLD 4 COOKING)', 'Coconuts'), 
('CORIANDER LEAVES', 'Coriander'), 
('FRESH  CORN  C>NCOB   t40#  AVGl', 'Corn'), 
('FRESH CORN ON COB (40# AVG)', 'Corn'), 
('C::ORRIANDER   LEAVES', 'Coriander'), 
('CC>RRIANDER  LEAVES', 'Coriander'), 
('CORR.IANDER   LEAVES', 'Coriander'), 
('CORRIANDER  LEAVES', 'Coriander'), 
('CORRIANDER LEAVES', 'Coriander'), 
('MUSHROOM CREMINI', 'Crimini Mushroom'), 
('CUCUMBERS 50 LB BOX', 'Cucumber'), 
('CUCUMBERS 60 LB BOX', 'Cucumber'), 
('CUCUMBERS HOT HOUSE', 'Cucumber - Cello'), 
('CUCUMBERS ENGLISH WRAPPED', 'Cucumber - English'), 
('CUCUMBERS KIRBY (45LB)', 'Cucumber - Kirby'), 
('CUCUMBERS LARGE', 'Cucumber - Large'), 
('CUCUMBER PERSIAN', 'Cucumber - Persian'), 
('Cucumber', 'Cucumber'), 
('CUCUMBERS', 'Cucumber'), 
('CUCUMBERS SMALL', 'Cucumber - Small'), 
('VVHITE   DAIKON  RADISH', 'Daikon Radish'), 
('VVHITE  DAIKC>N  RADISH', 'Daikon Radish'), 
('WHITE  DAIKC>N  RADISH', 'Daikon Radish'), 
('WHITE DAIKON RADISH', 'Daikon Radish'), 
('WHITE DAIKON RADISH ROUND', 'Daikon Radish'), 
('WHITE DAIMON RADISH', 'Daikon Radish'), 
('WHITE DAIMON RAMSH. .', 'Daikon Radish'), 
('WHITE DAIKON RADISH LONG', 'Daikon Radish - Long'), 
('WHITE DAIKON RADISH 40 LB BOX', 'Daikon Radish - White'), 
('FRESH DILL', 'Dill'), 
('FRESH DILL                        *1 POUND SMALLEST SIZE AVAIL*', 'Dill'), 
('DRAGON FRUIT', 'Dragon Fruit'), 
('DRAGON FRUIT 10 # BOX', 'Dragon Fruit'), 
('DRAGON FRUIT, 10Ib PER CASE', 'Dragon Fruit'), 
('DRAGONFRUIT 10# *CANNOT BREAK*', 'Dragon Fruit'), 
('DRAGON FRUIT 10#', 'Dragon Fruit'), 
('DRAGONFRUIT', 'Dragon Fruit'), 
('EGGPLANT', 'Eggplant'), 
('EGGPLANT 25 LB BOX', 'Eggplant'), 
('EGGPLANT LONG', 'Eggplant'), 
('EGGPLANT OBLONG', 'Eggplant'), 
('EGGPLANT SMALL SIZE', 'Eggplant - Small Size'), 
('EGGS FRESH FREE RANGE', 'Eggs Free Range'), 
('EGGS FRESH FREE RANGE XL', 'Eggs Free Range'), 
('ENDIVE 22 LBS.', 'Endive'), 
('ESCAROLE (22#/BX)', 'Escarole (22#/bx)'), 
('FRESH FENNEL', 'Fennel'), 
('FRESH FENNEL (24 HD)', 'Fennel (24 hd)'), 
('GALIA MELON', 'Galia Melon'), 
('GALIA MELON 11 PCS PER BOX', 'Galia Melon'), 
('GALIA MELON 34#', 'Galia Melon - 34#'), 
('GALIA MELONS', 'Galia Melon'), 
('GALIA MELONS (11 CT)', 'Galia Melon - 11ct'), 
('FRESH PEELED GARLIC 5 LB', 'Garlic'), 
('Garlic', 'Garlic'), 
('GARLIC CHOPPED GALLON', 'Garlic Chopped'), 
('GARLIC SUPER COLOSSAL', 'Garlic Super Colossal'), 
('FRESH  GINGER  ROOT', 'Ginger'), 
('FRESH GINGER ROOT', 'Ginger'), 
('GRAPEFRUIT', 'Grapefruit'), 
('GRAPEFRUIT 40 LB BOX PINK', 'Grapefruit'), 
('GRAPEFRUIT 40 LB BOX RED', 'Grapefruit'), 
('GRAPEFRUIT PINK', 'Grapefruit'), 
('GRAPEFRUIT RED', 'Grapefruit'), 
('GRAPEFRUIT RED 40 LB BOX', 'Grapefruit'), 
('GRAPFFIRLIIT PINK', 'Grapefruit - Pink'), 
('GRAPEFRUIT WHITE', 'Grapefruit - White'), 
('RED  SEEDLESS  GRAPES  122#\', 'Grapes - Red'), 
('RED SEEDLESS GRAPES (22#)', 'Grapes - Red'), 
('SEEDLESS  VVHITEGRAPES', 'Grapes - White'), 
('SEEDLESS WHITEGRAPES', 'Grapes - White'), 
('BLACK SEEDLESS GRAPES (22#)', 'Grapes - Black Seedless '), 
('RED SEEDLESS GRAPES', 'Grapes Red Seedless'), 
('RED SEEDLESS GRAPES ', 'Grapes Red Seedless'), 
('RED SEEDLESS GRAPES 22', 'Grapes Red Seedless'), 
('RED SEEDLESS GRAPES 22#', 'Grapes Red Seedless'), 
('RED.SEEDLESS GRAPES (22#)', 'Grapes Red Seedless'), 
('SEEDLESS WHITEGRAPES 22 LB BOX', 'Grapes White Seedless  '), 
('GRAPES WHITE SEEDLESS 22 LBS', 'GRAPES WHITE SEEDLESS 22 LBS'), 
('GRAPEFRUIT 40 LB BOX', 'Grapefruit'), 
('GRAPEFRUIT YELLOW', 'Grapefruit'), 
('GRAPEFRUIT 40 LB BOX * RED', 'Grapefruit Red'), 
('GUAVA', 'Guava'), 
('GUAVA 10 KGS BOX', 'Guava'), 
('GUAVA 13LB BOX', 'Guava'), 
('GUAVA 16#', 'GUAVA 16#'), 
('HONEY DEW', 'Honeydew'), 
('GOLDEN HONEY DEW MELONS', 'Honeydew Golden'), 
('HC>NEVDEVV  MELONS  20  LBS', 'Honeydew Melons'), 
('HONEYDEW MELONS 20 LB$', 'Honeydew Melons'), 
('HONEYDEW MELONS 20 LBS', 'Honeydew Melons'), 
('FRESH HORSE RADDISH', 'Horse Radish'), 
('FRESH HORSE RADISH', 'Horse Radish'), 
('FRESH HORSERADISH', 'Horseradish'), 
('JACK FRUIT', 'JACK FRUIT'), 
('JACK FRUIT 35 LBS BOX', 'Jack Fruit'), 
('WHOLE JACK FRUIT', 'Jack Fruit'), 
('JACKFRUIT', 'Jackfruit'), 
('KALE FRESH', 'KALE FRESH'), 
('FRESH kIWI', 'Kiwi'), 
('FRESH KIWI', 'Kiwi'), 
('FRESH KIWI (10 AVG)', 'Kiwi'), 
('FRESH KIWI (10# AVG)', 'Kiwi'), 
('FRESH KIWI (10#AVG)', 'Kiwi'), 
('FRESH KIWI (104 AVG)', 'Kiwi'), 
('FRESH KIWI (10tt AVG)', 'Kiwi'), 
('KIWI', 'Kiwi'), 
('LEEKS', 'Leeks'), 
('LEEKS 20 LB BOX', 'Leeks'), 
('LEEKS WHITE', 'Leeks'), 
('LEMON  GR.ASS', 'Lemon Grass'), 
('LEMON GRASS', 'Lemon Grass'), 
('SUNKIST LEMONS', 'Lemon sunkist'), 
('LEMONS', 'Lemons'), 
('LEMONS 40 LBS', 'Lemons'), 
('CELLO WRAPPED ICEBERG LETTUCE', 'Lettece Iceberg'), 
('LOLLO ROSSO LETTUCE 2 LB', 'Lettece Lollo Rosso'), 
('ICEBERG  LETTUCE', 'Lettuce - Iceberg'), 
('ICEBERG LETTUCE', 'Lettuce - Iceberg'), 
('FRESH ROMAINE LETTUCE', 'Lettuce - Romaine'), 
('BOSTON LETTUCE', 'Lettuce Boston'), 
('BOSTON LETTUCE /BUTTER LETTUCE', 'Lettuce Boston'), 
('BOSTON LETTUCE 24 HEADS', 'Lettuce Boston'), 
('LETTUCE BOSTON', 'Lettuce bOSTON'), 
('LETTUCE BUTTERCRUNCH', 'Lettuce Butter Crunch'), 
('FRISBEE LETUCE HEAD 2 LB/BX', 'Lettuce Frisee'), 
('FRISEE LETTUCE', 'Lettuce Frisee'), 
('LETTUCE GREEN  LEAF (24HD)', 'Lettuce Green Leaf'), 
('LETTUCE GREEN LEAF (24HD)', 'Lettuce Green leaf'), 
('ICEBERG LETTUCE 45 LB BOX', 'Lettuce Iceberg'), 
('LOLLO ROSSO LETTUCE 2#', 'Lettuce Lollo  Rosso 2#'), 
('LETTUCE LOLLO BIONDA', 'LETTUCE LOLLO BIONDA'), 
('LOLLO ROSS LETTUCE', 'Lettuce Lollo Rossa'), 
('LOLLO ROSSO LETTUCE 2# BOX', 'lettuce lollo rossa'), 
('LETTUCE LOLLO ROSSO 2LB', 'Lettuce Lollo Rosso'), 
('LETTUCE LOLLO ROSSO 2#', 'LETTUCE LOLLO ROSSO 2#'), 
('LETTUCE OAKLEAF', 'Lettuce Oak Leaf'), 
('LETTUCE OAKLEAF (2.5LB/BX)', 'Lettuce Oak Leaf'), 
('OAKLEAF LETTUCE HEAD 2 LB/BX', 'Lettuce Oak Leaf'), 
('LETTUCE OAKLEAF (2.5LBIBX)', 'LETTUCE OAKLEAF (2.5LBIBX)'), 
('LETTUCE RADICCHO 10#', 'LETTUCE RADICCHO 10#'), 
('MICRO CUT RAINBOW MIX', 'Lettuce Rainbow Mix'), 
('LETTUCE RED LEAF (24HD)', 'Lettuce red Leaf'), 
('RED LEAF HEAD LETTUCE', 'Lettuce Red Leaf'), 
('BABY RED OAK LETTUCE', 'Lettuce Red oak'), 
('RED OAK  LETTUCE', 'Lettuce Red Oak'), 
('FRESH ROMAINE LETTUCE', 'Lettuce Romaine'), 
('FRESH ROMAINE LETTUCE 40 LB   BOX', 'Lettuce Romaine'), 
('FRESH ROMAINE LETTUCE 40 LB/BX', 'Lettuce Romaine'), 
('FRESH ROMAINE LETTUCE 40 LBIBX', 'Lettuce Romaine'), 
('HEARTS OF ROMAINE', 'Lettuce Romaine'), 
('ROMAINE LETTUCE', 'Lettuce Romaine'), 
('FRESH ROMAINE LETTUCE *5 PCS*', 'Lettuce Romaine 5 hds'), 
('RUCCOLA', 'Lettuce RUCCOLA'), 
('SPRING MIX/MESCULLIN', 'Lettuce Spring Mix'), 
('FRESH  LIMES  110#  AVG.)', 'Limes'), 
('FRESH LIMES (10# AVG.)', 'Limes'), 
('LOLLO ROSSO', 'LOLLO ROSSO'), 
('LOLLO ROSSO 2#', 'LOLLO ROSSO 2#'), 
('LOLLO ROSSO 2LB', 'LOLLO ROSSO 2LB'), 
('MANGOES FRESH 10 LBS', 'Mangoes'), 
('MANGOES FRESH 10 LBS YELLOW', 'MANGOES FRESH 10 LBS YELLOW'), 
('CANARYNELLOW MELON 20#', 'Melon Canary Yellow'), 
('CANARYNELLOW MELON APPROX', 'Melon Canary Yellow'), 
('DINO MELON', 'Melon Dino'), 
('GALIA MELONS RIPE', 'Melon Galia'), 
('GALIA MELON APPROX 25#', 'Melon Galia 25 lb'), 
('MELORENGE MELON', 'Melon Melorenge'), 
('FRESH MINT', 'Mint'), 
('BUTTON MUSHROOMS 10 LB BOX', 'Mushroom Button'), 
('SHITAKE MUSHROOM 3 LB', 'Mushroom Shitake'), 
('FRESH  MUSHROOMS', 'Mushrooms'), 
('FRESH MUSHROOMS', 'Mushrooms'), 
('FRESH MUSHROOMS 10 LB BOX', 'Mushrooms'), 
('FRESH MUSTARD LEAVES', 'Mustard'), 
('MUSTARD GREENS', 'MUSTARD GREENS'), 
('NECTARINES', 'Nectaries'), 
('NECTARINES 28 LB BOX', 'Nectarine'), 
('FRESH  OKRA  15   LBS', 'Okra'), 
('FRESH OKRA 15 LBS', 'Okra'), 
('FRESH OKRA 16 LBS', 'Okra'), 
('CHINESE OKRA', 'Okra Chinese'), 
('INDIAN OKRA', 'Okra Indian'), 
('DRY YELLOW ONIONS MED.', 'Onion'), 
('WHITE PEARL ONION', 'Onion Pearl White'), 
('RED ONIONS 25 LB BOX', 'Onion Red'), 
('RED ONIONS LARGE SIZE', 'Onion Red Large'), 
('SHALLOT 10#', 'Onion Shallot'), 
('LARGE SPANISH ONION', 'Onion Spanish Large'), 
('LARGE SPANISH ONION 50 LB', 'Onion Spanish Large'), 
('DRY WHITE ONIONS', 'Onion White'), 
('WHITE PEARL ONION 25 LB BOX', 'Onion White Pearls'), 
('DRY YELLOW ONIONS 50LBS MEDIUM', 'Onion Yellow '), 
('DRY YELLOW ONIONS LARGE', 'Onion Yellow '), 
('DRY YELLOW ONIONS SIZE', 'Onion Yellow '), 
('RED ONIONS', 'Onions - Red'), 
('DRY  VELLOVV  ONIONS', 'Onions - Yellow'), 
('DRY YELLOW ONIONS', 'Onions - Yellow'), 
('DRY YELLOW ONIONS 50 LB', 'Onions - Yellow'), 
('RED ONIONS LARGE', 'Onions Red Large'), 
('DRY YELLOW ONIONS 50LBS', 'Onions yellow'), 
('ORANGES  40 LBS', 'Orange'), 
('ORANGES 40 LBS', 'Orange'), 
('SUNKIST ORANGE(88ct) VALENCIA', 'Orange Subkist 88'), 
('SUNKIST ORANGE', 'Orange Sunkist'), 
('SUNKIST ORANGE 88L0 40 LB BOX', 'Orange Sunkist'), 
('SUNKIST ORANGE(880', 'Orange SUNKIST'), 
('SUNKIST ORANGE(88ct) 40 LB BOX', 'Orange Sunkist'), 
('SUNKIST ORANGE 88ct', 'Orange Sunkist 88'), 
('SUNKIST ORANGE(88ct)', 'Orange Sunkist 88'), 
('ORANGES  SOCT  40  LBS', 'Oranges'), 
('ORANGES  SOCT  4-0LEIS', 'Oranges'), 
('ORANGES 80 CT 40 LBS', 'Oranges'), 
('FRESH OREGANO BUNCH', 'OREGANO'), 
('FRESH PAPAYA', 'Papaya'), 
('FRESH PAPAYA  10# AVG', 'Papaya'), 
('FRESH PAPAYA (10# AVG)', 'Papaya'), 
('FRESH PAPAYA (10# AVG) RIPE', 'Papaya'), 
('FRESH PAPAYA (100 AVG)', 'Papaya'), 
('FRESH PAPAYA(10# AVG)HALF-RIPE', 'Papaya'), 
('FRESH PAPAYA110# AVG)', 'Papaya'), 
('FRESHPAPAYA(10# AVG)10 PER CS NOT RIPE', 'Papaya'), 
('FRESH COOKING PAPAYA (40#)', 'Papaya Cooking'), 
('PARSLEY', 'Parsley'), 
('PARSLEY CURLY', 'Parsley'), 
('PARSLEY CURLEY', 'Parsley Curley'), 
('PARSLEY FLAT ITALIAN', 'PARSLEY FLAT ITALIAN'), 
('PARSNIPS', 'Parsnips'), 
('PARSNIPS(20#AVG)', 'Parsnips'), 
('PEACHES', 'Peaches'), 
('PEACHES 25 LBS', 'Peaches'), 
('PEACHES25 LBS', 'PEACHES25 LBS'), 
('BOSC STEWING PEARS', 'Pear Bosc'), 
('CHINESE PEAR 30# BOX', 'Pear Chineses'), 
('JAPANESE PEAR 40 LB BOX', 'Pear Japanese'), 
('pears', 'Pears'), 
('PEARS  4-0LBS', 'Pears'), 
('PEARS 40 LBS', 'Pears'), 
('PEARS 40 LBS', 'Pears'), 
('PEARS 40 LBS', 'Pears'), 
('PEARS 40 LBS (HALF RIPE)', 'Pears'), 
('PEARS 40 LBS GREEN', 'Pears'), 
('PEARS40  LBS', 'Pears'), 
('PEARS 40 LBS GREN RIPE', 'Pears Green'), 
('YELLOW PEARS 40 LBS', 'Pears Yellow'), 
('HOT  CHILI  PEPPERS', 'Pepper - Chili'), 
('HOT CHILI PEPPERS', 'Pepper - Chili'), 
('HOT CHILI PEPPERS GREEN', 'Pepper - Chili Green'), 
('RED HOT CHILI PEPPERS', 'Pepper - Chili Red'), 
('GREEN  BELL  PEPPERS', 'Pepper - Green Bell'), 
('GREEN BELL PEPPERS', 'Pepper - Green Bell'), 
('JALAPENO  PEPPERS', 'Pepper - Jalapeno'), 
('RED BELL PEPPER', 'Pepper - Red Bell'), 
('YELLOW BELL PEPPER', 'Pepper - Yellow'), 
('YELLOW PEPPER', 'Pepper - Yellow'), 
('CAYENNE PEPPER', 'Pepper Cayenne'), 
('FRESH CAYENNE PEPPER', 'Pepper Cayenne '), 
('CAYENNE PEPPER GREEN', 'Pepper Cayenne Green'), 
('GREEN CAYENNE PEPPERS', 'Pepper Cayenne Green'), 
('BIRD''S EYE CHILI', 'Pepper Chili Birds Eye'), 
('HOT CHILI PEPPERS GREEEN', 'Pepper Chili Green'), 
('HOT CHILI PEPPERS GREEN SMALL', 'Pepper Chili Green'), 
('HOT CHILI PEPPERS SMALL GREEN', 'Pepper Chili Green'), 
('HOT CHILI PEPPERS * RED', 'Pepper Chili Red'), 
('HOT CHILI PEPPERS JALAPENO', 'Pepper Chili Red'), 
('HOT CHILI PEPPERS RED', 'Pepper Chili Red'), 
('GREEN BELL PEPPERS 25 LB BOX', 'Pepper Green '), 
('LONG HOT CHILI PEPPERS SPANISH', 'Pepper Green Long Hot'), 
('HOT CHILI PEPPERS GREEN PADI', 'Pepper Green Pad Thia hot'), 
('JALAPENO', 'Pepper Jalapeno'), 
('JALAPENO CHILI PEPPERS', 'Pepper Jalapeno '), 
('GREEN JALAPENO PEPPERS', 'Pepper Jalapeno Green'), 
('RED JALAPENO PEPPERS', 'Pepper Jalapeno Red'), 
('LONG CHILI PEPPERS', 'Pepper Long Chili'), 
('POBLANO CHILI PEPPERS', 'Pepper Ploblano'), 
('JALAPENO RED HOT CHILI PEPPERS', 'Pepper Red Chili'), 
('RED HOT CHILI PEPPERS LONG', 'Pepper Red Chili Long'), 
('RED HOT CHILI PEPPERS SMALL', 'Pepper Red Chili Small'), 
('LONG RED HOT CHILI PEPPERS', 'Pepper Red Long Hot'), 
('RED HOT CHILI PEPPERS THAI', 'Pepper Red Thai Hot '), 
('THAI HOT CHILI/PEPPERS', 'Pepper Thai Hot '), 
('THAI CHILI//PEPPER', 'Pepper Thai Red'), 
('THAILAND RED CHILI PEPPERS', 'Pepper Thai Red'), 
('CHILLI PADI GREEN', 'Pepper, Padi Green'), 
('HOT CHILI PEPPERS CAYENNE', 'Peppers Cayenne'), 
('HOT CHILI PEPPERS GREEN Cayenne', 'Peppers Cayenne'), 
('PIMIENTO (RED CHERRY PEPPER)', 'Peppers Cherry Red'), 
('XTRA HOT CHILI PEPPERS', 'Peppers Chili Extra Hot'), 
('HOT CHILI PEPPERS GREN', 'Peppers Chili Green'), 
('HOT CHILI PEPPERS GREEN LARGE', 'Peppers Chili Green Large'), 
('RED HOT CHILI PEPPERS JALAPENO', 'Peppers Chili Hot Jalapeno'), 
('HOT CHILI PEPPER SPANISH GREEN', 'Peppers Chili Spanish Green'), 
('EXTRA HOT CHILI PEPPERS', 'Peppers Chili Xhot'), 
('HOT CHILI PEPPERS XHOT', 'Peppers Chili Xhot'), 
('PEPPERS CUBANELLE', 'PEPPERS CUBANELLE'), 
('GREENBELL PEPPERS', 'Peppers Green Bell'), 
('JALAPENO PEPPERS', 'Peppers Jalapeno'), 
('XTR HOT CHILI PEPPERS', 'Peppers XHOT Chili'), 
('Yellow Peppers', 'Peppers Yellow'), 
('FRESH PINEAPPLE 20 LB BOX', 'Pineapple'), 
('FRESH PINEAPPLE GOLD', 'Pineapple'), 
('FRESH PINEAPPLE (6CT)', 'Pineapple 6 count'), 
('FRESH PINEAPPLE** DOLE BRAND', 'Pineapple Dole only'), 
('FRESH PINEAPPLE', 'Pineapples'), 
('FRESH PINEAPPLE', 'Pineapples'), 
('FRESH PINEAPPLE "DOLE"', 'Pineapples'), 
('FRESH PINEAPPLE (6 CT)', 'Pineapples'), 
('FRESH PINEAPPLE 6 CT', 'Pineapples'), 
('Pineapples', 'Pineapples'), 
('PLANTAIN COOKING BANANA 45 LB', 'Plantain'), 
('PLANTAIN COOKING BANANA', 'PLANTAIN COOKING BANANA'), 
('PLANTAINS', 'PLANTAINS'), 
('Plum', 'Plum'), 
('PLUMS', 'Plums'), 
('PLUMS .', 'Plums'), 
('PLUMS 28 LB BOX', 'Plums'), 
('POMEGRANATE', 'Pomegranate'), 
('POMELO (35 - 40 LBS BOX)', 'Pomelo'), 
('BABY POTATOES 50 LB', 'Potato Baby'), 
('BABY YELLOW POTATOES', 'Potato Baby Yellow'), 
('RUSSET BAKING POTATOES 50 LB', 'Potato Baking Russet'), 
('IDAHO BAKING POTATOES 50 LB/BG', 'Potato Idaho'), 
('RED POTATOES', 'Potato Red'), 
('RED POTATOES 50 LB', 'Potato Red'), 
('BABY RED YUKON POTATO', 'Potato Red Baby'), 
('SMALL RED POTATO 50#', 'Potato Small Red C from store'), 
('SWEET POTATOES 40 LB BOX', 'Potato Sweet'), 
('NEW WHITE POTATOES 50 LB BAG', 'Potato White'), 
('NEW WHITE POTATOES 50LBS', 'Potato White'), 
('NEW WHITE POTATOES 50LBS LARGE', 'Potato White'), 
('LARGE SIZE YELLOW POTATO, 50#', 'Potato Yukon'), 
('IDAHO BAKING POTATOES', 'Potatoes - Idaho'), 
('SVVEET  POTATOES', 'Potatoes - Sweet'), 
('SWEET POTATOES', 'Potatoes - Sweet'), 
('NEVV  VVHITE  POTATOES', 'Potatoes - White'), 
('NEVV  WHITE  POTATOES', 'Potatoes - White'), 
('NEW WHITE POTATOES', 'Potatoes - White'), 
('NEW WHITE POTATOES 50 LB', 'Potatoes - White'), 
('NEW WHITE POTATOES  LARGE', 'Potatoes - White Large'), 
('NEW WHITE POTATOES LARGE', 'Potatoes - White Large'), 
('WHITE POTATOES', 'Potatto White'), 
('PUMPKINS 40 LB BOX YELLOW', 'Pumkin'), 
('PUMPKINS RED', 'Pumkin Red Acorn'), 
('PUMPKINS SMALL', 'Pumkin Small'), 
('PUMPKINS 40 LB BOX * YELLOW', 'Pumkin Yellow'), 
('PUMPKINS YELLOW', 'Pumkin Yellow'), 
('PUMPKINS YELLOW 40 LB BOX', 'Pumkin Yellow'), 
('PUMPKINS 40 LB BOX', 'Pumpkin'), 
('PUMPKINS  VVHITE', 'Pumpkin - White'), 
('PUMPKINS 40 LB BOX * RED', 'Pumpkin Red'), 
('PUMPKINS', 'Pumpkins'), 
('PUMPKINS ', 'Pumpkins'), 
('PUMPKINS WHITE', 'PUMPKINS WHITE'), 
('RED RADISHES 6 OZ BAGS', 'Radish - Red'), 
('RED RADISHES 6 02 BAGS', 'Red Radishes'), 
('RIDGE GOURD', 'Ridge Gourd  '), 
('RIDGE GOURD 1 CHINESE OKRA 30#', 'RIDGE GOURD 1 CHINESE OKRA 30#'), 
('HEARTS OF ROMAINE (12/3PKT)', 'Romaine Hearts'), 
('FRESH ROSEMARY BUNCH', 'Rosemary'), 
('RUCOLA LETTUCE', 'Rucola Baby Arrugula'), 
('WINTER/SAVOY CABBAGE', 'Savoy Cabbage'), 
('SCULLIC>NfSPR.ING  ONION)  1/3  LBS', 'Scallion Onions'), 
('SCULLIC>NtSPR.ING  ONION\   "1/3  LBS', 'Scallion Onions'), 
('SCULLION(SPRING ONION) 1/3 LBS', 'Scallion Onions'), 
('SCULLION(SPRING ONION) 113 LBS', 'Scallion Onions'), 
('SCULLION SPRING ONION', 'Scallions'), 
('SCULLION SPRING ONION) ', 'Scallions'), 
('SCULLION SPRING ONION) 1/3 LBS', 'Scallions'), 
('SCULLION(SPRING ONION)', 'Scallions'), 
('SCULLION(SPRING ONION) 1 13 LBS', 'Scallions'), 
('SCULLION(SPRING ONION) 1/3 LBS', 'Scallions'), 
('SCULLION(SPRING ONION) 113 Las', 'Scallions'), 
('SCULLION1SPRING ONION) 1/3 LBS', 'Scallions'), 
('SCULLIONISPRING ONION) 1/3 LBS', 'Scallions'), 
('Scullions', 'Scallions'), 
('SCULLIQN(SPRING ONION) 1/3 LBS', 'Scallions'), 
('SHALLOT ONION, 10#', 'SHALLOT ONION, 10#'), 
('SNAKE GOURD', 'Snake Gourd'), 
('FRESH SNOW PEA', 'Sno Pea'), 
('FRESH SNOW PEA (10#_AVG)', 'Sno Pea'), 
('FRESH SNOW PEA (100 AVG)', 'Sno Peas'), 
('FRESH SNOW PEA (10# AVG)', 'Snow Pea'), 
('BABY SPINACH LEAVES (412.5LB)', 'Spinach'), 
('FRESH  SPINACH', 'Spinach'), 
('FRESH SPINACH', 'Spinach'), 
('FRESH SPINACH 10 LB BOX', 'Spinach'), 
('FRESH SPINACH 25 LB BOX', 'Spinach'), 
('FRESH BABY SPINACH', 'Spinach Baby'), 
('FRESH SPINACH BABY', 'Spinach Baby'), 
('BABY SPINACH', 'Spinach Baby  3 lb box'), 
('FRESH SPINACH BABY CLEANED', 'Spinach Baby Cleaned 2.5 lb bag'), 
('FRESH CELLO SPINACH', 'Spinach Cello'), 
('SPRING MIX 3LBS CASE', 'Spring Mix'), 
('SPRING MIXIMESCULLIN 3LB', 'Spring mix'), 
('MICRO CUT RAINBOW MIX 80Z', 'Spring Mix Rainbow Micro'), 
('BUTTERNUT SQUASH', 'Squash'), 
('ACORN SQUASH', 'Squash Acorn'), 
('ACORN SQUASH 45 LB BOX', 'Squash Acorn'), 
('ACORN SQUASH (RED PUMPKIN)', 'Squash Acorn Red Pumpkin'), 
('BUTTERNUT SQUASH 45 LB BOX WHITE LONG', 'Squash Butternut'), 
('BUTTERNUT SQUASH YELLOW LONG', 'Squash Butternut'), 
('BUTTERNUT YELOW SQUASH', 'Squash Butternut'), 
('BUTTERNUT SQUASH GREEN', 'Squash Butternut Green'), 
('BUTTERNUT SQUASH(WHITE PUMPKIN', 'Squash Butternut white pumplkin'), 
('BUTTERNUT SQUASH YELLOW', 'Squash Butternut Yellow'), 
('CALABASSA SQUASH', 'Squash Calabassa'), 
('LONG WHITE SQUASH', 'Squash Lomg White'), 
('PUMPKIN SQUASH', 'Squash Pumpkin'), 
('YELLOW SQUASH', 'Squash Yellow'), 
('YELLOW SQUASH 22 LB BOX', 'Squash Yellow'), 
('ZUCCHINI SQUASH WHITE', 'Squash Yellow'), 
('YELLOW SQUASH LONG NECK', 'Squash Yellow Zucchini'), 
('STRAWBERRIES (12 PIS) 12 LB BX', 'Strawberries'), 
('STRAWBERRIES (12 PTS) 12 LB BX', 'Strawberries'), 
('STRAWBERRIES 12 PTS)', 'Strawberries'), 
('STRAWBERRIES 8 LB CASE', 'Strawberries'), 
('STRAWBERRIES NIA', 'Strawberries'), 
('STRAWBERRIES (12 PIS)', 'STRAWBERRIES (12 PIS)'), 
('STRAWBERRIES  (12 PTS)', 'STRAWBERRIES (12 PTS)'), 
('STRAWBERRIES (12 PTS)', 'STRAWBERRIES (12 PTS)'), 
('STRAWBERRY N/A', 'STRAWBERRY'), 
('STRING  BEANS', 'String Beans'), 
('STRING BEANS', 'String Beans'), 
('STRING BEANS 25 LB BOX', 'String Beans'), 
('STRING BEANS 26 LB BOX', 'String Beans'), 
('SUNKIST ORANGE(88ct) 40 LB BOX * VALENCIA', 'Sunkist Orange Valencia'), 
('TANGERINES (MANDARIN ES NIA)', 'Tangerine Mandarin'), 
('TANGERINES', 'Tangerines'), 
('TANGERINES 40 LB BOX', 'Tangerines'), 
('TANGERINES ( MANDARINES  N/A)', 'Tangerines - Mandarin'), 
('TANGERINES (MANDARINES N/A)', 'Tangerines - Mandarin'), 
('FRESH TARO ROOT', 'Taro Root'), 
('FRESH THYME', 'Thyme'), 
('FRESH THYMES 1KG', 'Thyme'), 
('FRESH THYME 2.2#', 'Thyme 2.2 lb'), 
('FRESH THYME BUNCH', 'Thyme Fresh Bunch'), 
('TOMATOES *UNRIPE* 25 LB BOX', 'Tomato'), 
('TOMATOES 1(2 RIPE', 'Tomato'), 
('TOMATOES 1/2 RIPE 25 LB BOX', 'Tomato'), 
('TOMATOES 1/2 RIPE BEEFSTEAK', 'Tomato'), 
('TOMATOES 112 RIPE', 'Tomato'), 
('TOMATOES 112 RIPE 25 LB BOX', 'Tomato'), 
('TOMATOES 25 LB BOX', 'Tomato'), 
('TOMATOES BACKWARDS 1/2 RIPE', 'Tomato'), 
('TOMATOES RIPE 25 LB BOX', 'Tomato'), 
('CHERRY TOMATOES (12/PINTS)', 'Tomato - Cherry'), 
('BEEF STEAK TOMATOES', 'Tomato Beef Stake'), 
('TOMATO BEEFSTEAK', 'Tomato Beefstake'), 
('TOMATOES BEEFSTAKE', 'Tomato Beefstake'), 
('Cherry Tomato', 'Tomato Cherry'), 
('CHERRY TOMATOES', 'Tomato Cherry'), 
('CHERRY TOMATOES (121PINTS)', 'Tomato Cherry'), 
('CHERRY TOMATOES 12/PINTS', 'Tomato Cherry'), 
('ROMA TOMATOES', 'Tomato Plum'), 
('TOMATO PLUM ROMANO RED', 'Tomato Plum'), 
('TOMATOES RED', 'Tomato Red'), 
('TOMATOES 112 RIPE RED', 'Tomato RIPE'), 
('TOMATOES', 'Tomatoe'), 
('TOMATOES   "1/2  RIPE', 'Tomatoes'), 
('TOMATOES  1/2  RIPE', 'Tomatoes'), 
('TOMATOES *FULL* RIPE', 'Tomatoes'), 
('TOMATOES 1/2 RIPE', 'Tomatoes'), 
('TOMATOES BACKWARD', 'Tomatoes'), 
('CHERRYTOMATOES (421PINTS)', 'Tomatoes Cherry'), 
('TOMATOES ON THE VINE', 'TOMATOES ON THE VINE'), 
('YELLOW TURNIPS', 'Turnip Yellow Rutabagus'), 
('WHITE TURNIPS', 'Turnips - White'), 
('yELLOW TURNIPS 50 LB BOX', 'Turnips Yellow'), 
('Watermellon', 'Watermellon'), 
('VVATER.MELONS', 'Watermelons'), 
('VVATERMELC>NS', 'Watermelons'), 
('Watermelon', 'Watermelons'), 
('WATERMELONS', 'Watermelons'), 
('WATERMELONS SWEET RED', 'Watermelons'), 
('WAX BEANS/YELLOW BEANS', 'Wax Beans'), 
('WHITE TURNIPS 20 LB BOX', 'White Turnips'), 
('WINTER GOURD', 'Winter Gourd'), 
('YELLOW LONG', 'Yellow Long'), 
('YELLOW SQUASH STRAIGHT NECK', 'Yellow Squash'), 
(' ZUCCHINI SQUASH', 'Zucchini Squash'), 
('.ZUCCHINI  SQUASH', 'Zucchini Squash'), 
('ZUCCHINI  SQUASH', 'Zucchini Squash'), 
('ZUCCHINI SQUASH', 'Zucchini Squash'), 
('ZUCCHINI SQUASH 22 LB BOX', 'Zucchini Squash'), 
('ZUCCHINI SQUASH GREEN', 'Zucchini Squash'), 
('PEARS 40 LB', 'Pears'), 
('FRESH KIWI  ', 'Kiwi'), 
('SCULLION(SPRING ONIO', 'Scallions'), 
('JALAPENO PEPPERS *GREEN*', 'Pepper - Jalapeno'), 
('CREW PRIVATE', 'CREW PRIVATE'), 
('ZUCCHINI SQUASH 22 LB BOX       ', 'Squash Green'), 
('TOMATOES RED 25 LB BOX', 'Tomato'), 
('GALIA MELON 6 CT', 'Melon Galia'), 
('FRENCH BEANS 5 LB BOX', 'Beans French 5 lb'), 
('PUMPKINS 40 LB BOX GREEN', 'Pumpkin Green'), 
('PUMPKINS 40 LB BOX RED', 'Pumpkin Red'), 
('FRESH CELLO SPINACH 12 LB BOX', 'Spinach'), 
('ROCKET LETTUCE', 'BABY ARUGULA (ROCKET)'), 
('FRESH AVOCADO (25 LB/BX)', 'Avocado'), 
('FRESH ORANGE', 'Orange'), 
('NECTARINES 25 LB BOX', 'Nectarines'), 
('BANANAS * GREEN 40 LB BOX', 'Banana - **Green**'), 
('GRAPEFRUIT 40 LB BOX * PINK', 'Grapfruit Pink'), 
('RED POTATOES 50 LB BAG', 'Potato Red'), 
('YELLOW POTATOS/YUKON POTATO', 'Potato Yukon'), 
('JACKFRUIT YOUNG SMALL', 'Jackfruit Small'), 
('STRAWBERRIES 8 LB BX', 'Stawberry'), 
('SHALLOTS, NON PEELED', 'Shallot , Non Peeled'), 
('BOC CHOI FRESH 40 LB *BABY', 'Boc Choi ***Baby'), 
('GALA APPLES', 'Apple Gala'), 
('PUMPKINS 40 LB BOX ** WHITE', 'Pumpkin White'), 
('FRESH ARUGULA', 'Arugula, Baby'), 
('PUMPKINS 40 LB BOX WHITE', 'Pumpkin White'), 
('JALEPENO PEPPERS', 'Pepper Jalapeno'), 
('PARSLEY * CURLEY', 'Parsley Curly'), 
('FRESH CASSAVA ROOT', 'Cassava Root'), 
('Jalapeno Pepper', 'Pepper Jalapeno'), 
('GREEN BELL PEPPERS * LARGE FOR STUFFING', 'Peppers Green Large'), 
('FRESH GUAVA', 'Guava'), 
('RED GRAPEFRUIT', 'Grapefruit Red'), 
('ORANGES 40 LBS NAVEL', 'Orange Navel'), 
('BROAD BEANS FRESH', 'Beans Broad '), 
('SWEET POTATOES 40 LB BOX * PURPLE', 'Potato Sweet Purple'), 
('LETTUCE LOLLO ROSSO', 'Lettuce Lollo Rossa'), 
('SPRING MIX LETTUCE', 'Lettuce Spring Mix'), 
('GALA APPLES 40 LBS', 'Apple Gala'), 
('BUTTERNUT SQUASH 45LB WHITE', 'Butternut Squash'), 
('MUSTARD GREENS 20 LB BOX', 'Greens Mustard'), 
('SPONGE GOURD', 'Sponge Gourd'), 
('SPRING ONIONS', 'Scallions'), 
('Bitter Melon', 'Bitter Melon/Gourd'), 
('Brocolli', 'Brocolli'), 
('Iceberg sub Romaine', 'Romaine Lettuce'), 
('Okra', 'Okra'), 
('Green Peppers', 'Pepper Green'), 
('Red Peppers', 'Pepper Red'), 
('Chili Peppers Green', 'Pepper Chili Green'), 
('Red Radish', 'Red Radishes'), 
('Spinach', 'Spinach'), 
('Green Squash', 'Green Squash'), 
('BIRDSEYE CHILI', 'Pepper Birdseye'), 
('YELLOW SQUASH 45 LB BOX', 'Yellow Squash '), 
('FRESH DRAGONFRUIT', 'Dragonfruit'), 
('FRESH ROSEMARY', 'Rosemary'), 
('SPRING MIX 3 LB BAG', 'Spring Mix'), 
('RED SQUASH 45 LB BOX', 'Squash Red'), 
('FRESH ROSMARY', 'Rosemary'), 
('LONG HOT CHILI PEPPERS', 'Pepper Long Hot Chili'), 
('THYME FRESH', 'Thyme'), 
('GARLIC STEMS/SCAPES', 'Garlic Stem\Scapes'), 
('PARSLEY * CURLY', 'Parsley - Curley');

